POST http://localhost:8085/content/myBucket/myFilename
Content-Type: application/json

{
  "actionParams": {
    "name": "MyErrorFormatAction"
  },
  "deltaFile": {
    "did": "cde6dbcd-10a5-4393-bb85-bb6c2f9a66d3",
    "created": "2021-08-10T20:05:20.175Z",
    "modified": "2021-08-10T20:05:20.207Z",
    "stage": "EGRESS",
    "domains": [
      {
        "key": "error",
        "value": "{}"
      }
    ],
    "sourceInfo": {
      "filename": "input",
      "flow": "smoke",
      "metadata": [
        {
          "key": "filename",
          "value": "df2cf33c-3363-4ab6-b535-96d5cc990ba1"
        },
        {
          "key": "flow",
          "value": "smoke"
        }
      ]
    },
    "protocolStack": [
      {
        "type": "binary",
        "objectReference": {
          "offset": 0,
          "size": 2560,
          "name": "cde6dbcd-10a5-4393-bb85-bb6c2f9a66d3/ingress-df2cf33c-3363-4ab6-b535-96d5cc990ba1",
          "bucket": "storage"
        },
        "metadata": []
      }
    ],
    "actions": [
    ]
  }
}

###

GET http://localhost:8085/content/myBucket/myFilename?offset=10&size=100
