"TUI Build":
  tags:
    - light
  extends:
    - .golang
  stage: build
  script:
    - |
      pushd tui
      make debug-make build
      popd
      ls -la ../../deltafi
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH

"TUI Test":
  tags:
    - light
  extends:
    - .golang
  stage: build
  when: manual
  script:
    - |
      pushd tui
      make debug-make test
      popd
      ls -la ../../deltafi
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH
