{{ if .Values.enabled }}
{{- if .Values.extensions.cache.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.name }}-extensions-cache
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.operator.name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
{{- if .Values.serviceAccount.repoCredentials }}
imagePullSecrets:
{{- range .Values.serviceAccount.repoCredentials }}
- name: {{ . }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operator.name }}-extensions-cache
  annotations:
    meta.helm.sh/release-name: {{ .Values.operator.name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["stackgres.io"]
  resources:
  - sgclusters
  - sgdistributedlogs
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operator.name }}-extensions-cache
  annotations:
    meta.helm.sh/release-name: {{ .Values.operator.name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}-extensions-cache
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.operator.name }}-extensions-cache
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.operator.name }}-extensions-cache
  annotations:
    meta.helm.sh/release-name: {{ .Values.operator.name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: ["", "apps"]
  resources:
  - serviceaccounts
  - statefulsets
  verbs:
  - get
  - patch
  - update
  resourceNames:
  - {{ .Values.operator.name }}-extensions-cache
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - delete
  resourceNames:
  - {{ .Values.operator.name }}-extensions-cache-0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.operator.name }}-extensions-cache
  annotations:
    meta.helm.sh/release-name: {{ .Values.operator.name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.name }}-extensions-cache
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.operator.name }}-extensions-cache
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
