{{ if .Values.enabled }}
{{- if .Values.extensions.cache.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.operator.name }}-extensions-cache
  annotations:
    meta.helm.sh/release-name: {{ .Values.operator.name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.operator.name }}-extensions-cache
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
{{- end }}
{{- end }}
