#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: export-system-plans

Usage:
  export-system-plans"
  exit 1
}

ARGS=("$@")
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

PLANNAME=${ARGS[@]:1}
[[ ${#ARGS[@]} -gt 1 ]] && cli_help_command

# Do not include 'sourcePlugin (PluginCoordinates)' in the projections
# below, since they are no part of the input needed by load/import.
QUERY="
fragment ActionFields on ActionConfiguration {
  name
  type
  parameters
}

{
  getAllSystemFlowPlans {
    dataSinkPlans {
      name
      type
      description
      subscribe {
        topic
        condition
      }
      egressAction {
        ...ActionFields
      }
    }
    restDataSources {
      name
      type
      description
      topic
    }
    timedDataSources {
      name
      type
      description
      topic
      timedIngressAction {
        ...ActionFields
      }
      cronSchedule
    }
    transformPlans {
      name
      type
      description
      subscribe {
        topic
        condition
      }
      transformActions {
        ...ActionFields
      }
      publish {
        matchingPolicy
        defaultRule {
          defaultBehavior
          topic
        }
        rules {
          topic
          condition
        }
      }
    }
  }
}
"

RESULT=$(deltafi cli query "$QUERY")
DGS_ERRORS=$(echo $RESULT | jq -r "select(.errors) | .errors[] | .message")
if [[ "$DGS_ERRORS" != "" ]]; then
  cli_log "${red}${BASENAME}: Failed to export system plans${normal}"
  echo -e "${red}Error: ${DGS_ERRORS}${normal}"
else
  echo "$RESULT" | jq '.data.getAllSystemFlowPlans'
fi
