#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: export-data-sink-plan

Usage:
  export-data-sink-plan DATA_SINK_PLAN_NAME"
  exit 1
}

ARGS=("$@")
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

PLANNAME=${ARGS[@]:1}
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command

QUERY="fragment ActionFields on ActionConfiguration {
          name
          type
          parameters
        }

        query {
          getDataSinkPlan(planName: \"$PLANNAME\") {
            name
            type
            description
            sourcePlugin {
              groupId
              artifactId
              version
            }
            subscribe {
              topic
              condition
            }
            egressAction {
              ... ActionFields
            }
          }
        }
        "

RESULT=$(deltafi cli query "$QUERY")
DGS_ERRORS=$(echo $RESULT | jq -r "select(.errors) | .errors[] | .message")
if [[ "$DGS_ERRORS" != "" ]]; then
  cli_log "${red}${BASENAME}: Failed to export data sink plan: $PLANNAME${normal}"
  echo -e "${red}Error: ${DGS_ERRORS}${normal}"
else
  echo "$RESULT" | jq '.data.getDataSinkPlan'
fi
