#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: export-plan

Usage:
  export-plan FLOW_PLAN_NAME"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

PLANNAME=${ARGS[@]:1}
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command

QUERY="query { exportFlowPlan(name: \"$PLANNAME\") }"

RESULT=$(deltafi query $QUERY)
echo "$RESULT" | jq '.data.exportFlowPlan'
