#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: export-rest-data-source-plan

Usage:
  export-rest-data-source-plan REST_DATA_SOURCE_PLAN_NAME"
  exit 1
}

ARGS=("$@")
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

PLANNAME=${ARGS[@]:1}
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command

QUERY="query {
          getRestDataSourcePlan(planName: \"$PLANNAME\") {
            name
            type
            description
            sourcePlugin {
              groupId
              artifactId
              version
            }
            topic
            metadata
            annotationConfig {
              annotations
              metadataPatterns
              discardPrefix
            }
          }
        }
        "

RESULT=$(deltafi cli query "$QUERY")
DGS_ERRORS=$(echo $RESULT | jq -r "select(.errors) | .errors[] | .message")
if [[ "$DGS_ERRORS" != "" ]]; then
  cli_log "${red}${BASENAME}: Failed to export rest data source plan: $PLANNAME${normal}"
  echo -e "${red}Error: ${DGS_ERRORS}${normal}"
else
  echo "$RESULT" | jq '.data.getRestDataSourcePlan'
fi
