#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: list-plans

Usage:
  list-plans [OPTIONS]

Options:
  -h, --help     Show help"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " || " ${ARGS[@]} " =~ " -h " ]] && cli_help_command

QUERY="query { getAllFlowPlans { ingressPlans { name description sourcePlugin {groupId artifactId version}} egressPlans { name description sourcePlugin {groupId artifactId version}}}}"
RESULT=$(deltafi query "$QUERY")

print_plans() {
  echo "$RESULT" | jq -r "([\"${1^} Flow Plan\", \"Source Plugin\", \"Description\"] | (., map(length*\"=\"))), (.data.getAllFlowPlans.$1Plans[] | [.name, (.sourcePlugin.groupId + \":\" + .sourcePlugin.artifactId + \":\" + .sourcePlugin.version), .description]) | @tsv" | column -ts $'\t'
}

DGS_ERRORS=$(echo $RESULT | jq -r "select(.errors) | .errors[] | .message")
if [[ "$DGS_ERRORS" != "" ]]; then
  cli_log "${red}${BASENAME}: Failed to get the list of flow plans${normal}"
  echo -e "${red}Error: ${DGS_ERRORS}${normal}"
else
  print_plans "ingress"
  echo
  print_plans "egress"
fi