#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: load-plan

Usage:
  load-plan PLAN_FILE"
  exit 1
}

TMPFILE="/tmp/.deltafi-load-plan.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

trap cleanup INT

MUTATION="saveFlowPlan"
POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      cli_help_command
      shift # past argument
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters
ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command
FILE=${ARGS[@]:1}

if [ ! -f "$FILE" ]; then
  cli_log "${yellow}${FILE}: No such file${normal}"
  exit 1
fi

BASENAME="$(basename $FILE)"
JSON=$(cat "$FILE")
VARIABLES="{\"flowPlan\": $JSON }"

QUERY="mutation(\$flowPlan: FlowPlanInput!) {${MUTATION}(flowPlan: \$flowPlan) { name }}"
DELTAFI_DGS=$(deltafi serviceip deltafi-core-domain-service)
POST_QUERY="{ \"query\": \"$QUERY\",\"variables\":$VARIABLES}"

truncate --size 0 ${TMPFILE}
RESPONSE_CODE=$(curl -s -X POST -o ${TMPFILE} -w "%{http_code}" -H "Content-Type: application/json" -d "$POST_QUERY" http://$DELTAFI_DGS/graphql)

if [[ "$RESPONSE_CODE" != "200" ]]; then
  cli_log "${red}${BASENAME}: Loading flow plan failed${normal}"
  echo -e "${red}${RESPONSE_CODE} Error: $(cat ${TMPFILE})${normal}"
else
  ERRORS=$(cat ${TMPFILE} | jq -r "select(.errors) | .errors[] | .message")
  if [[ "$ERRORS" != "" ]]; then
    cli_log "${red}${BASENAME}: Loading flow plan failed${normal}"
    echo -e "${red}Error: ${ERRORS}${normal}"
  else
    cli_log "Successfully loaded flow plan from file ${cyan}${BASENAME}${normal}"
  fi
fi

cleanup
