#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: mongo-migrate

Usage:
  mongo-migrate"
  exit 1
}

KUBECTL_BIN="kubectl"
POD=$(${KUBECTL_BIN} get pod -l app.kubernetes.io/name=mongodb -o jsonpath="{.items[0].metadata.name}")

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
MONGODB_USERNAME_ENV='$MONGODB_USERNAME'
MONGODB_PASSWORD_ENV='$MONGODB_PASSWORD'
${KUBECTL_BIN} exec -it ${POD} -- sh -c "rm -rf /opt/migrations && mkdir /opt/migrations"
for i in ${DELTAFI_DIR}/migrations/*.js; do
  ${KUBECTL_BIN} cp ${i} ${POD}:/opt/migrations
  ${KUBECTL_BIN} exec -it ${POD} -- sh -c "mongo -u ${MONGODB_USERNAME_ENV} --password ${MONGODB_PASSWORD_ENV} deltafi < /opt/migrations/$(basename ${i})"
done
