#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: mongo-migrate

Usage:
  mongo-migrate"
  exit 1
}

POD=$(${KUBECTL_BIN} get pod -l app.kubernetes.io/name=mongodb -o jsonpath="{.items[0].metadata.name}")
MIGRATION_DIR="/tmp/migrations"

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
MONGODB_USERNAME_ENV='$MONGODB_USERNAME'
MONGODB_PASSWORD_ENV='$MONGODB_PASSWORD'
${KUBECTL_BIN} exec -i ${POD} --container mongodb -- sh -c "rm -rf ${MIGRATION_DIR} && mkdir ${MIGRATION_DIR}"
for i in ${DELTAFI_DIR}/migrations/*.js; do
  cli_log "Running database migration $(basename ${i})"
  ${KUBECTL_BIN} cp --container mongodb ${i} ${POD}:${MIGRATION_DIR}
  ${KUBECTL_BIN} exec -i ${POD} --container mongodb -- sh -c "mongo -u ${MONGODB_USERNAME_ENV} --password ${MONGODB_PASSWORD_ENV} --quiet deltafi ${MIGRATION_DIR}/$(basename ${i})"
done
