#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: postgres-cli

Usage:
  postgres-cli"
  exit 1
}

shift
PARAMS="${*@Q}"
echo "ARGS: $ARGS PARAMS: $PARAMS"
if _is_standalone; then
  echo "Not implemented for standalone mode"
else
  ${KUBECTL_BIN} exec -it "$(${KUBECTL_BIN} get pod --selector application=spilo,spilo-role=master -o name)" -c postgres -- psql ${PARAMS} -U deltafi deltafi
fi
