#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: redis-cli

Usage:
  redis-cli"
  exit 1
}

KUBECTL_BIN="kubectl"

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
REDIS_PASSWORD_ENV='$REDIS_PASSWORD'
${KUBECTL_BIN} exec -it deltafi-redis-master-0 -- sh -c "redis-cli --no-auth-warning -a $REDIS_PASSWORD_ENV"
