#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: secrets

Usage:
  secrets [NAME]"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

SECRETS=${ARGS[@]:1}

KUBECTL_BIN="kubectl"
KUBECTL_CMD="${KUBECTL_BIN} get secrets --namespace ${DELTAFICLI_K8S_NAMESPACE}"

if [ -z ${SECRETS} ]; then
  SECRETS=$(${KUBECTL_CMD} --field-selector type=Opaque  | grep -v "^NAME" | awk '{ print $1 }' | xargs)
fi

for SECRET in ${SECRETS}; do
  echo "---- ${SECRET} ----"
  FIELDS=$(${KUBECTL_CMD} ${SECRET} -o json | jq -e '.data | keys | join(" ")' -r)
  for FIELD in ${FIELDS}; do
    VALUE=$(${KUBECTL_CMD} ${SECRET} -o json | jq -e ".data.\"${FIELD}\"" -r | base64 -d)
    printf "%-30s%-4s\n"  "${FIELD}" "${VALUE}";
  done
  echo
done
