#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: serviceip

Usage:
  serviceip SERVICE"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

SERVICE=${ARGS[@]:1}
[[ ${#ARGS[@]} -lt 2 ]] && cli_help_command

KUBECTL_CMD="${KUBECTL_BIN} get services -o wide"
IP=$($KUBECTL_CMD | grep $SERVICE | tail -n 1 | awk '{print $3}')
echo $IP
