#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: set-admin-password

Usage:
  set-admin-password [PASSWORD]"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

PASSWORD=${ARGS[@]:1}
if [[ ${#ARGS[@]} -lt 2 ]]; then
  echo -n "Password: "
  read -s PASSWORD
  echo
fi

ADMIN_ID="00000000-0000-0000-0000-000000000000"
API_V2=$(_api_v2)
QUERY="{\"password\":\"${PASSWORD}\"}"

RESPONSE_CODE=$(curl -s -XPUT -H "Content-Type: application/json" -H "$PERMISSION" -H "$CLI_USER" -o /dev/null -w "%{http_code}" -d $QUERY $API_V2/users/$ADMIN_ID)

if [[ "$RESPONSE_CODE" == "200" ]]; then
  cli_log "${cyan}Admin password set successfully${normal}"
else
  cli_log "${red}Setting admin password failed${normal}"
fi
