#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: timed-data-source

Subcommands:
  start
  stop
  validate
  show
Expert-only Subcommands:
  clear-memo
  set-memo
Usage:
  timed-data-source [SUBCOMMAND] DATA_SOURCE_NAME [MEMO]
  Only set-memo uses MEMO argument"
  exit 1
}

TMPFILE="/tmp/.deltafi-timed-data-source.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

log_failed() {
  cli_log "${red}${BASENAME}: Failed to ${SUBCOMMAND} timedDataSource: ${DATA_SOURCE_NAME}${normal}"
  echo -e "${red}Error: ${1}${normal}"
}

trap cleanup INT

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      cli_help_command
      shift # past argument
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters
ARGS=("$@")
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
[[ ${#ARGS[@]} -lt 3 ]] && cli_help_command
SUBCOMMAND=${ARGS[1]}
DATA_SOURCE_NAME=${ARGS[2]}

VARIABLES="{\"name\": \"$DATA_SOURCE_NAME\", \"memo\": \"$MEMO\" }"
case "$SUBCOMMAND" in
  clear-memo)
    echo -e "${yellow}Warning: ${SUBCOMMAND} for experts only${normal}"
    _are_you_sure
    EXTRACT_PATH=".data.setTimedDataSourceMemo"
    QUERY="mutation(\$name: String!) { setTimedDataSourceMemo(name: \$name) }"
    ;;
  set-memo)
    [[ -z "$MEMO" ]] && _exit_1 echo "Please specify a value for MEMO"
    echo -e "${yellow}Warning: ${SUBCOMMAND} for experts only${normal}"
    _are_you_sure
    EXTRACT_PATH=".data.setTimedDataSourceMemo"
    QUERY="mutation(\$name: String!, \$memo: String) { setTimedDataSourceMemo(name: \$name, memo: \$memo) }"
    ;;
  start)
    EXTRACT_PATH=".data.startTimedDataSource"
    QUERY="mutation(\$name: String!) { startTimedDataSource(name: \$name) }"
    ;;
  stop)
    EXTRACT_PATH=".data.stopTimedDataSource"
    QUERY="mutation(\$name: String!) { stopTimedDataSource(name: \$name) }"
    ;;
  validate)
    EXTRACT_PATH=".data.validateTimedDataSource"
    QUERY="query(\$name: String!) {validateTimedDataSource(name: \$name) { flowStatus { state errors { configName errorType message } } } }"
    ;;
  show)
    EXTRACT_PATH=".data.getTimedDataSource"
    QUERY="query(\$name: String!) {
             getTimedDataSource(name: \$name) {
                 name
                 type
                 description
                 sourcePlugin {
                   groupId
                   artifactId
                   version
                 }
                 flowStatus {
                   state
                   errors {
                     configName
                     errorType
                     message
                   }
                   testMode
                 }
                 maxErrors
                 topic
                 ... on TimedDataSource {
                   cronSchedule
                   lastRun
                   nextRun
                   memo
                   currentDid
                   executeImmediate
                   ingressStatus
                   ingressStatusMessage
                   timedIngressAction {
                     name
                     apiVersion
                     actionType
                     type
                     parameters
                   }
                   variables {
                     name
                     description
                     dataType
                     required
                     defaultValue
                     value
                     masked
                   }
                 }
             }
           }"
    ;;
  *)
    cli_help_command
    ;;
esac

DELTAFI_DGS=$(_graphql)
QUERY=$(echo $QUERY | sed 's/"/\\"/g')
POST_QUERY="{ \"query\": \"$QUERY\",\"variables\":$VARIABLES}"

truncate -s 0 ${TMPFILE}
RESPONSE_CODE=$(curl -s -X POST -o ${TMPFILE} -w "%{http_code}" -H "Content-Type: application/json" -H "$PERMISSION" -H "$CLI_USER" -d "$POST_QUERY" "$DELTAFI_DGS")

if [[ "$RESPONSE_CODE" != "200" ]]; then
  ERRORS=$(cat ${TMPFILE})
  log_failed "$ERRORS"
else
  DGS_ERRORS=$(cat ${TMPFILE} | jq -r "select(.errors) | .errors[] | .message")
  if [[ "$DGS_ERRORS" != "" ]]; then
    log_failed "$DGS_ERRORS"
  elif  [[ "$SUBCOMMAND" == "validate" || "$SUBCOMMAND" == "show" ]]; then
    cat ${TMPFILE} | jq -r "${EXTRACT_PATH}"
  else
    STARTED=$(cat ${TMPFILE} | jq -r "${EXTRACT_PATH}")
    if [[ $STARTED == "true" ]]; then
      cli_log "Successfully executed ${SUBCOMMAND} for data source ${cyan}${DATA_SOURCE_NAME}${normal}"
    else
      cli_log "${yellow}Data source ${DATA_SOURCE_NAME} did not ${SUBCOMMAND}.${normal}"
    fi
  fi
fi

cleanup
