#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: timed-data-source

Subcommands:
  start
  stop
  validate
  show
Expert-only Subcommands:
  clear-memo
  set-memo
Usage:
  timed-data-source [SUBCOMMAND] FLOW_NAME [MEMO]
  Only set-memo uses MEMO argument"
  exit 1
}

TMPFILE="/tmp/.deltafi-timed-data-source.$$"

cleanup() {
  rm -f $TMPFILE
  exit
}

log_failed() {
  cli_log "${red}${BASENAME}: Failed to ${SUBCOMMAND} flow ${cyan}${FLOW_NAME}${normal}"
  echo -e "${red}Error: ${1}${normal}"
}

trap cleanup INT

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      cli_help_command
      shift # past argument
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL[@]}" # restore positional parameters
ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
[[ ${#ARGS[@]} -lt 3 ]] && cli_help_command
SUBCOMMAND=${ARGS[1]}
FLOW_NAME=${ARGS[2]}
MEMO=${ARGS[3]}

VARIABLES="{\"name\": \"$FLOW_NAME\", \"memo\": \"$MEMO\" }"
case "$SUBCOMMAND" in
  clear-memo)
    echo -e "${yellow}Warning: ${SUBCOMMAND} for experts only${normal}"
    _are_you_sure
    EXTRACT_PATH=".data.setTimedDataSourceMemo"
    QUERY="mutation(\$name: String!) { setTimedDataSourceMemo(name: \$name) }"
    ;;
  set-memo)
    [[ -z "$MEMO" ]] && _exit_1 echo "Please specify a value for MEMO"
    echo -e "${yellow}Warning: ${SUBCOMMAND} for experts only${normal}"
    _are_you_sure
    EXTRACT_PATH=".data.setTimedDataSourceMemo"
    QUERY="mutation(\$name: String!, \$memo: String) { setTimedDataSourceMemo(name: \$name, memo: \$memo) }"
    ;;
  start)
    deltafi data-source start "$FLOW_NAME"
    exit 0
    ;;
  stop)
    deltafi data-source stop "$FLOW_NAME"
    exit 0
    ;;
  validate)
    deltafi data-source validate "$FLOW_NAME"
    exit 0
    ;;
  show)
    deltafi data-source show "$FLOW_NAME"
    exit 0
    ;;
  *)
    cli_help_command
    ;;
esac

DELTAFI_DGS=$(deltafi serviceip deltafi-core-service)
QUERY=$(echo $QUERY | sed 's/"/\\"/g')
POST_QUERY="{ \"query\": \"$QUERY\",\"variables\":$VARIABLES}"

truncate -s 0 ${TMPFILE}
RESPONSE_CODE=$(curl -s -X POST -o ${TMPFILE} -w "%{http_code}" -H "Content-Type: application/json" -H "$PERMISSION" -H "$CLI_USER" -d "$POST_QUERY" http://$DELTAFI_DGS/graphql)

if [[ "$RESPONSE_CODE" != "200" ]]; then
  ERRORS=$(cat ${TMPFILE})
  log_failed "$ERRORS"
else
  DGS_ERRORS=$(cat ${TMPFILE} | jq -r "select(.errors) | .errors[] | .message")
  if [[ "$DGS_ERRORS" != "" ]]; then
    log_failed "$DGS_ERRORS"
  elif  [[ "$SUBCOMMAND" == "validate" || "$SUBCOMMAND" == "show" ]]; then
    cat ${TMPFILE} | jq -r "${EXTRACT_PATH}"
  else
    cat ${TMPFILE}
    STARTED=$(cat ${TMPFILE} | jq -r "${EXTRACT_PATH}")
    if [[ $STARTED == "true" ]]; then
      cli_log "Successfully executed ${SUBCOMMAND} for flow ${cyan}${FLOW_NAME}${normal}"
    else
      cli_log "${yellow}Flow ${FLOW_NAME} did not ${SUBCOMMAND}.${normal}"
    fi
  fi
fi

cleanup
