#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: uninstall

Usage:
  uninstall"
  exit 1
}

ARGS=("$@")
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

_k8s_uninstall() {
  # perform a helm uninstall
  helm uninstall $DELTAFICLI_PROJECT_NAME

  # sweep up whatever helm missed, but keep secrets
  $KUBECTL_BIN delete pods,daemonsets,services,statefulsets,replicasets,deployments,poddisruptionbudgets -n deltafi --grace-period=0 --force --all 2>&1 | grep -v Warning
  $KUBECTL_BIN patch pv deltafi-postgres -p '{"spec":{"claimRef": null}}'
}

_compose_uninstall() {
  "${DELTAFICLI_COMPOSE_PATH}"/compose uninstall
}

read -r -p "☢️  Uninstalling DeltaFi is a destructive operation that will remove configuration and anything in the database.
☠️  This could make your day go badly.
Are you really, really sure? [y/N] " response
case "$response" in
  [yY][eE][sS]|[yY])
    cli_log "Uninstalling DeltaFi"
    if _is_standalone; then
      _compose_uninstall
    else
      _k8s_uninstall
    fi
    ;;
  *)
    cli_log "Aborting uninstall"
    exit 0
    ;;
esac

cli_log "DeltaFi uninstall complete"
