#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: valkey-watch

Usage:
  valkey-watch"
  exit 1
}

ARGS=("$@")
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
VALKEY_PASSWORD_ENV='$REDIS_PASSWORD'
GREP_CMD='grep -v "^OK$\|AUTH\|ping"'

if _is_standalone; then
  docker exec -it deltafi-valkey sh -c "valkey-cli --no-auth-warning -a $VALKEY_PASSWORD_ENV monitor 2>&1 | $GREP_CMD"
else
  ${KUBECTL_BIN} exec -it deltafi-valkey-master-0 -- sh -c "valkey-cli --no-auth-warning -a $VALKEY_PASSWORD_ENV monitor 2>&1 | $GREP_CMD"
fi
