#!/usr/bin/env bash

. "$DELTAFICLI_WORKDIR/common"

cli_help_command() {
  echo "
Command: versions

Usage:
  versions"
  exit 1
}

ARGS=($@)
[[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command

KUBECTL_BIN="kubectl"
KUBECTL_CMD="${KUBECTL_BIN} get pods --namespace ${DELTAFICLI_K8S_NAMESPACE}"

${KUBECTL_CMD} -o json \
  | jq -r '.items[] | [(.metadata.labels."app.kubernetes.io/name", .metadata.labels.app | select(. != null) )][0] as $app | .spec.containers[] | [$app, .name, .image | split(":")] | flatten | @csv' \
  | sort -u | sed 's/\\"//g' | sed 's/"//g' | sed '1 i\===,=========,=====,===' | sed '1 i\App,Container,Image,Tag' | column -t -s ','
