ui:eslint:
  tags:
    - light
  image: node:alpine
  stage: build
  needs: []
  retry: 2
  script:
    - cd deltafi-ui
    # Install ui dependencies
    - |
      npm install
    # Run eslint
    - npm run lint

ui:license:
  tags:
    - light
  image: node
  stage: build
  needs: []
  script:
    - ./deltafi-ui/licenseCheck.sh

.ui:
  variables:
    PROJECT_NAME: deltafi-ui

ui:docker:
  stage: docker
  needs: []
  extends:
    - .ui
    - .docker

ui:docker-multiarch:
  stage: docker
  needs: []
  extends:
    - .ui
    - .docker-multiarch

ui:test:
  image: deltafi/deltafi-ui-test
  stage: test
  needs:
    - job: "ui:eslint"
  retry: 2
  script:
    - cd deltafi-ui
    # link node_modules from base image
    - ln -s /app/node_modules ./node_modules
    # start the server (with mocking enabled) in the background
    - VUE_APP_MOCK_RESPONSES=successResponse VUE_APP_MOCK_REQUEST_DELAY=1 npm run dev &
    # wait for the server to start
    - npx wait-on -t 120000 http://127.0.0.1:8080
    # run Cypress tests
    - npx cypress run --e2e --config video=false
