ui:eslint:
  tags:
    - light
  image: node
  stage: build
  needs: []
  script:
    - cd deltafi-ui
    # Install eslint
    - |
      npm install eslint eslint-plugin-vue
    # Run eslint
    - npm run lint

ui:license:
  tags:
    - light
  image: node
  stage: build
  needs: []
  script:
    - ./deltafi-ui/licenseCheck.sh

.ui:
  variables:
    PROJECT_NAME: deltafi-ui

ui:docker:
  stage: docker
  needs: []
  extends:
    - .ui
    - .docker

ui:docker-multiarch:
  stage: docker
  needs: []
  extends:
    - .ui
    - .docker-multiarch
