eslint-ui:
  image: node
  stage: build
  needs: []
  script:
    - cd deltafi-ui
    # Install eslint
    - |
      npm install eslint eslint-plugin-vue
    # Run eslint
    - npm run lint

license-ui:
  image: node
  stage: build
  needs: []
  script:
    - ./deltafi-ui/licenseCheck.sh

.core:
  variables:
    PROJECT_NAME: deltafi-ui

ui:docker:
  stage: docker
  needs: []
  extends:
    - .core
    - .docker

ui:docker-multiarch:
  stage: docker
  needs: []
  extends:
    - .core
    - .docker-multiarch
