{
 "title": "System Overview",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Graphite Data", "query": "graphite" },
   {
    "name": "dfDataSource",
    "label": "Data Source",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Ingress/Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sum(summarize(seriesByTag('name=stats_counts.bytes_from_source', 'dataSource=~${dfDataSource:regex}'), '$__interval', 'sum', false))"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_from_source', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sum(summarize(seriesByTag('name=stats_counts.bytes_to_sink', 'dataSource=~${dfDataSource:regex}'), '1h', 'sum', false))"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.bytes_from_source', 'dataSource=~${dfDataSource:regex}')), 'Overall Bytes')"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.bytes_to_sink', 'dataSource=~${dfDataSource:regex}')), 'Overall Egress Bytes')"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maximumAbove(sortByTotal(aliasByTags(groupByTags(summarize(seriesByTag('name=stats_counts.bytes_from_source', 'dataSource=~${dfDataSource:regex}'), '$__interval', 'sum', false), 'sum', 'dataSource'), 'dataSource')), 0)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "maximumAbove(sortByTotal(aliasByTags(groupByTags(summarize(seriesByTag('name=stats_counts.bytes_to_sink', 'dataSource=~${dfDataSource:regex}'), '$__interval', 'sum', false), 'sum', 'dataSource'), 'dataSource')), 0)"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_to_sink', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_from_source', 'dataSource=~${dfDataSource:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_to_sink', 'dataSource=~${dfDataSource:regex}')), 'Egress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_filtered', 'dataSource=~${dfDataSource:regex}')), 'Filtered')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_dropped', 'dataSource=~${dfDataSource:regex}')), 'Dropped')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_errored', 'dataSource=~${dfDataSource:regex}')), 'Errored')"
    }
   ]
  },
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 20 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_from_source', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), '1min', 'sum', 'minutes'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Files Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 20 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_to_sink', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), '1min', 'sum', 'minutes'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Files Filtered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_filtered', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), '1min', 'sum', 'minutes'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Files Dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_dropped', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), '1min', 'sum', 'minutes'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Files Errored",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_errored', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), '1min', 'sum', 'minutes'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Files Retried",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_auto_resumed', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), '1min', 'sum', 'minutes'), 'dataSource'), true, false)"
    }
   ]
  },
  { "title": "DeltaFile Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "target": "alias(gauge.deltafile.totalCount, 'Total DeltaFiles')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "gauge.deltafile.totalCount" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sum(seriesByTag('name=gauge.node.disk.usage'))"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=gauge.node.disk.usage')), 'Disk Usage')"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlightCount, 'In Flight')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlightCount, 'Files in flight')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "gauge.deltafile.inFlightBytes" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlightBytes, 'In Flight')"
    }
   ]
  },
  { "title": "Action Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 } },
  {
   "title": "Action Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 53 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.action_execution'), 'sum', 'source'), 'source')"
    }
   ]
  },
  { "title": "Global Events", "type": "annolist", "gridPos": { "h": 22, "w": 8, "x": 0, "y": 62 } },
  {
   "title": "Action Execution Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 62 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.action_execution_time_ms', 'action!=ingress'), 'sum', 'source'), 'source')"
    }
   ]
  },
  {
   "title": "Action Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 71 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'))"
    }
   ]
  },
  { "title": "Disk Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Disk utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.disk.usage'), 'hostname', 'service'), true, true)"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "target": "aliasByTags(sortByName(seriesByTag('name=~gauge.node.disk'), true, true), 'hostname', 'service')"
    }
   ]
  },
  {
   "title": "Memory utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(maxSeries(sortByName(seriesByTag('name=~gauge.node.memory.limit'), true, true)), 'limit')"
    },
    {
     "target": "sortByMaxima(sortByName(aliasByTags(seriesByTag('name=~gauge.node.memory.usage'), 'hostname'), true, true))"
    }
   ]
  },
  {
   "title": "CPU utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(maxSeries(sortByName(seriesByTag('name=~gauge.node.cpu.limit'), true, true)), 'limit')"
    },
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.cpu.usage'), 'hostname'), true, true)"
    }
   ]
  },
  {
   "title": "DeltaFiles deleted by policy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=stats_counts.deleted.files'), 'policy')"
    }
   ]
  },
  {
   "title": "Bytes deleted by policy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=stats_counts.deleted.bytes'), 'policy')"
    }
   ]
  }
 ]
}