export const sidebar = [
  {
    text: "Introduction",
    link: "/",
  },
  {
    text: "Concepts",
    link: "/concepts",
  },
  {
    text: "Getting Started",
    collapsed: true,
    items: [
      { text: "Quick Start With Docker Compose", link: "/getting-started/quick-start" },
      { text: "Extending DeltaFi with Plugins", link: "/getting-started/install-plugins" },
      { text: "Creating a Simple Plugin", link: "/getting-started/simple-plugin" },
    ],
  },
  {
    text: "Installation",
    collapsed: true,
    items: [
      { text: "Docker Compose", link: "/install/compose" },
      { text: "Kubernetes", link: "/install/kubernetes" },
      { text: "KinD (Kubernetes in Docker)", link: "/install/kind" },
    ],
  },
  {
    text: "Configuration",
    collapsed: true,
    items: [{ text: "Authentication", link: "/config/authentication" }],
  },
  {
    text: "Plugins",
    collapsed: true,
    items: [
      { text: "Creating a Plugin", link: "/plugins" },
      { text: "Actions", link: "/actions" },
      { text: "Timed Ingress Action", link: "/actions/timed_ingress" },
      { text: "Transform Action", link: "/actions/transform" },
      { text: "Egress Action", link: "/actions/egress" },
      { text: "Flows", link: "/flows" },
      { text: "Action Parameters", link: "/action_parameters" },
      { text: "Lookup Tables", link: "/lookup_tables" },
      { text: "Action Unit Testing", link: "/unit-test" },
    ],
  },
  {
    text: "Core Actions",
    collapsed: true,
    items: [
      { text: "Annotate", link: "/core-actions/org.deltafi.core.action.annotate.Annotate" },
      { text: "Compress", link: "/core-actions/org.deltafi.core.action.compress.Compress" },
      { text: "Convert", link: "/core-actions/org.deltafi.core.action.convert.Convert" },
      { text: "Decompress", link: "/core-actions/org.deltafi.core.action.compress.Decompress" },
      { text: "Delay", link: "/core-actions/org.deltafi.core.action.delay.Delay" },
      { text: "DeleteContent", link: "/core-actions/org.deltafi.core.action.delete.DeleteContent" },
      { text: "Error", link: "/core-actions/org.deltafi.core.action.error.Error" },
      { text: "ExtractJson", link: "/core-actions/org.deltafi.core.action.extract.ExtractJson" },
      { text: "ExtractXml", link: "/core-actions/org.deltafi.core.action.extract.ExtractXml" },
      { text: "Filter", link: "/core-actions/org.deltafi.core.action.filter.Filter" },
      { text: "HttpEgress", link: "/core-actions/org.deltafi.core.action.egress.HttpEgress" },
      { text: "JoltTransform", link: "/core-actions/org.deltafi.core.action.jolt.JoltTransform" },
      { text: "Merge", link: "/core-actions/org.deltafi.core.action.merge.Merge" },
      { text: "MetadataToContent", link: "/core-actions/org.deltafi.core.action.metadata.MetadataToContent" },
      { text: "ModifyMediaType", link: "/core-actions/org.deltafi.core.action.mediatype.ModifyMediaType" },
      { text: "ModifyMetadata", link: "/core-actions/org.deltafi.core.action.metadata.ModifyMetadata" },
      { text: "Split", link: "/core-actions/org.deltafi.core.action.split.Split" },
      { text: "XmlEditor", link: "/core-actions/org.deltafi.core.action.xml.XmlEditor" },
      { text: "XsltTransform", link: "/core-actions/org.deltafi.core.action.xslt.XsltTransform" },
    ],
  },
  {
    text: "Operating",
    collapsed: true,
    items: [
      { text: "Ingress", link: "/operating/ingress" },
      { text: "TUI (Text User Interface)", link: "/operating/TUI" },
      { text: "GUI", link: "/operating/GUI" },
      { text: "Configuration", link: "/operating/configuration" },
      { text: "Error Handling", link: "/operating/errors" },
      { text: "Events API", link: "/operating/events_api" },
      { text: "Metrics", link: "/operating/metrics" },
      { text: "DeltaFile Analytics and Survey", link: "/operating/deltafile_analytics" },
    ],
  },
  {
    text: "Advanced Topics",
    collapsed: true,
    items: [
      { text: "Architecture", link: "/advanced/architecture" },
      { text: "Automatic Resume", link: "/advanced/auto_resume" },
      { text: "Advanced Routing", link: "/advanced/advanced_routing" },
      { text: "Data Retention", link: "/advanced/data_retention" },
      { text: "DeltaFile Annotations", link: "/advanced/deltafile_annotations" },
      { text: "Leader-Member Deployment", link: "/advanced/leader_member" },
      { text: "Multithreading Java Actions", link: "/advanced/multithreading_java_action_kit" },
    ],
  },
  { text: "KinD Cluster for Demo, Dev, and Test", link: "/kind" },
  { text: "Contributing to Core Development", link: "/contributing" },
  { text: "Changelog", link: "/CHANGELOG" },
];
