spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:deltafi}
      username: ${MONGO_USERNAME:deltafi}
      password: ${MONGO_PASSWORD:password}
      authentication-database: ${MONGO_AUTH_DB:admin}
      auto-index-creation: true
  task:
    scheduling:
      pool:
        # provide threads for scheduled redis long poll tasks
        size: 32

deltafi:
  namespace: deltafi
  requeueSeconds: 30
  delete:
    onCompletion: false
    frequency: PT1M
    policies:
      oneHourAfterComplete:
        type: ageOff
        parameters:
          afterComplete: PT1H
  housekeeping:
    initialDelaySeconds: 60
    delaySeconds: 3600
    objectMinimumAgeForRemovalSeconds: 900

minio:
  url: ${MINIO_URL:http://deltafi-minio:9000}
  access-key: ${MINIO_ACCESS:minioadmin}
  secret-key: ${MINIO_SECRET:minioadmin}
  part-size: ${MINIO_PART_SIZE:100000000}

redis:
  url: ${REDIS_URL:http://http://deltafi-redis-master:6379}
  password: ${REDIS_PASSWORD:redis}

zipkin:
  enabled: ${ZIPKIN_ENABLED:true}
  url: ${ZIPKIN_URL:http://deltafi-zipkin:9411/api/v2/spans}
  send-initial-delay-ms: ${ZIPKIN_SEND_INITIAL_DELAY:500}
  send-period-ms: ${ZIPKIN_SEND_PERIOD:500}
  max-batch-size: ${ZIPKIN_MAX_BATCH_SIZE:10000}
