#!/usr/bin/env bash

KUBECTL_BIN="kubectl --namespace ${DELTAFICLI_K8S_NAMESPACE}"

cli_log() {
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo ">> $timestamp $1"
}

normal=$(tput sgr0)
bold=$(tput bold)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
