spring:
  application:
    name: deltafi-core-actions
  main:
    web-application-type: none
    banner-mode: "off"
  mustache:
    check-template-location: false

logging:
  level:
    org.springframework.data.convert.CustomConversions: ERROR

actions:
  actionThreads:
    org.deltafi.core.action.egress.FlowfileEgress: 4
    org.deltafi.core.action.egress.RestPostEgress: 4
    org.deltafi.core.action.filter.Filter: 2