spring:
  application:
    name: deltafi-core-actions
  config:
    import: configserver:http://deltafi-core-service/config
  main:
    web-application-type: none
    banner-mode: "off"
  mustache:
    check-template-location: false

logging:
  level:
    org.springframework.data.convert.CustomConversions: ERROR
