.dgs:
  variables:
    PROJECT_NAME: deltafi-dgs

dgs:docker:
  stage: docker
  before_script:
    - rm $PROJECT_NAME/build/libs/${PROJECT_NAME}-*-api.jar
    - cp $PROJECT_NAME/build/libs/${PROJECT_NAME}-*.jar $PROJECT_NAME/build/libs/${PROJECT_NAME}.jar
  extends:
    - .dgs
    - .docker
  needs:
    - job: "build"

dgs:publish:
  stage: publish
  extends:
    - .dgs
    - .gradle
    - .publish
  needs:
    - job: "build"
  script: ${GRADLE} ${PROJECT_NAME}:publish

dgs:coverage_report:
  stage: publish
  extends:
    - .dgs
    - .coverage_report
  needs: ["build"]
  dependencies:
    - build

# include:
#  - template: Code-Quality.gitlab-ci.yml

# code_quality:
#   artifacts:
#     paths: [gl-code-quality-report.json]

# code_quality_html:
#   extends: code_quality
#   variables:
#     REPORT_FORMAT: html
#   artifacts:
#     expose_as: 'Code Quality Report'
#     paths: [gl-code-quality-report.html]

