.core-domain:
  variables:
    PROJECT_NAME: deltafi-core-domain

core-domain:docker:
  stage: docker
  extends:
    - .core-domain
    - .docker
  needs:
    - job: "build"

core-domain:publish:
  stage: publish
  extends:
    - .core-domain
    - .gradle
    - .publish
  needs:
    - job: "build"
  script: ${GRADLE} ${PROJECT_NAME}:publish

core-domain:coverage_report:
  stage: publish
  extends:
    - .core-domain
    - .coverage_report
  needs: ["build"]
  dependencies:
    - build

# include:
#  - template: Code-Quality.gitlab-ci.yml

# code_quality:
#   artifacts:
#     paths: [gl-code-quality-report.json]

# code_quality_html:
#   extends: code_quality
#   variables:
#     REPORT_FORMAT: html
#   artifacts:
#     expose_as: 'Code Quality Report'
#     paths: [gl-code-quality-report.html]

