apiVersion: batch/v1
kind: Job
metadata:
  name: register-deltafi-plugin
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: register-deltafi-plugin
        image: "badouralix/curl-jq"
        imagePullPolicy: IfNotPresent
        command: 
        - "/bin/sh"
        - "-c"
        - |
          echo "Registering {{ .Chart.Name }} plugin..."
          MUTATION="mutation(\$pluginInput: PluginInput!) {registerPlugin(pluginInput: \$pluginInput) {pluginCoordinates {artifactId}}}"
          JSON={{ .Files.Get "files/plugin.json" | replace "\n" "" | quote}}
          VARIABLES="{\"pluginInput\": $JSON}"
          POST_QUERY="{\"query\": \"$MUTATION\", \"variables\":$VARIABLES}"
          echo "Sending $POST_QUERY"
          RESPONSE_CODE=$(curl -s -o /tmp/register_response -X POST -w "%{http_code}" -H "Content-Type: application/json" -d "$POST_QUERY" http://deltafi-core-domain-service/graphql)
          if [[ "$RESPONSE_CODE" != "200" ]]; then
            echo "Registering plugin manifest failed" "Bad response code ($RESPONSE_CODE) with response $(cat /tmp/register_response)"
            exit 1
          fi
          cat /tmp/register_response
          echo "Success"
      restartPolicy: Never
