version: '3.8'

services:
  deltafi-dirwatcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: deltafi-dirwatcher:latest
    container_name: deltafi-dirwatcher
    volumes:
      # Mount the watch directory. Adjust the source path as needed
      - ./watched-dir:/watched-dir
    environment:
      # Required: The base URL of the DeltaFi core service
      - DELTAFI_URL=http://deltafi-core-service
      # Optional: The ingress API endpoint (default: /api/v2/deltafile/ingress)
      - DELTAFI_INGRESS_API=/api/v2/deltafile/ingress
      # Optional: Override the watch directory (default: /watched-dir)
      - DIRWATCHER_WATCH_DIR=/watched-dir
      # Optional: Number of concurrent workers (default: 5)
      - DIRWATCHER_WORKERS=10
      # Optional: Buffer size for file streaming in bytes (default: 32MB)
      - DIRWATCHER_BUFFER_SIZE=33554432
      # Optional: Maximum allowed file size in bytes (default: 2GB)
      - DIRWATCHER_MAX_FILE_SIZE=2147483648
      # Optional: Retry period in seconds for failed uploads (default: 300)
      - DIRWATCHER_RETRY_PERIOD=300
    restart: unless-stopped
    # Ensure the container has access to the deltafi network
    networks:
      - deltafi

networks:
  deltafi:
    name: deltafi
    external: true 
