# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awesome_print'
gem 'aws-sdk-s3'
gem 'filesize'
gem 'httparty'
gem 'k8s-ruby'
gem 'puma'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'

group :test, :development do
  gem 'pry'
  gem 'rack-test'
  gem 'rerun'
  gem 'rspec', '~> 3.0'
end
