# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '~> 7.0.8'
gem 'awesome_print'
gem 'aws-sdk-s3'
gem 'bytesize'
gem 'click_house'
gem 'connection_pool'
gem 'eventmachine', '~> 1.2.7'
gem 'filesize'
gem 'graphite-api'
gem 'httparty'
gem 'k8s-ruby', '~> 0.15.1'
gem 'mongoid'
gem 'oj', '~> 3.16.3'
gem 'rainbows'
gem 'redis'
gem 'rexml'
gem 'sinatra', '~> 3'
gem 'sinatra-contrib', '~> 3'
gem 'timers'

group :test, :development do
  gem 'pry'
  gem 'rack-test'
  gem 'rerun'
  gem 'rspec', '~> 3.0'
end
