# frozen_string_literal: true

source 'https://rubygems.org'

gem 'eventmachine', '~> 1.2.7'
gem 'httparty'
gem 'rainbows'
gem 'sinatra'
gem 'sinatra-contrib'

group :test, :development do
  gem 'pry'
  gem 'rack-test'
  gem 'rspec', '~> 3.0'
end
