{
 "title": "Action Log Viewer",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging",
  "DeltaFi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "action_name", "label": "Action", "query": "label_values(action)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"ACTION\", action=~\"$action_name\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=\"ACTION\", action=~\"$action_name\"} |~ `(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=~\".+\", type=~\"ACTION\", action=~\"$action_name\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  }
 ]
}