{
 "title": "Audit Log Viewer",
 "description": "Dashboard for audit logging",
 "tags": [
  "DeltaFi",
  "logging",
  "Loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" },
   { "name": "user", "label": "Users", "query": "label_values(user)" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "exclude_pattern", "label": "Exclude (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total Count of Audit Logs",
   "type": "stat",
   "description": "Total count of audit log lines in the specified time range",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({type=~\"AUDIT\", user=~\"$user\"} |~ `(?i)$searchable_pattern` !~ `(?i)$exclude_pattern|null` [$__interval]))"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(user) (count_over_time({type=\"AUDIT\", user=~\"$user\"} |~ `(?i)$searchable_pattern` !~ `(?i)$exclude_pattern|null` [1m]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Live Audit Logs",
   "type": "table",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{type=\"AUDIT\", user=~\"$user\"} |~ `(?i)$searchable_pattern` !~ `(?i)$exclude_pattern|null`"
    }
   ]
  }
 ]
}