{
 "title": "Clickhouse Flow by Annotation",
 "description": "Flow metrics grouped by the values in an annotation applied to the flows",
 "tags": [
  "DeltaFi",
  "Clickhouse"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "clickhouseDatasource", "label": "Clickhouse Datasource", "query": "grafana-clickhouse-datasource" },
   {
    "name": "flow",
    "label": "Flow",
    "query": "SELECT DISTINCT flow FROM deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )"
   },
   {
    "name": "annotation",
    "label": "Annotation",
    "query": "SELECT DISTINCT arrayJoin(mapKeys(annotations)) AS keys FROM deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and ( flow IN (${flow} ) )"
   },
   {
    "name": "subflow",
    "label": "Annotation Value",
    "query": "SELECT DISTINCT annotations['${annotation}'] AS subflow FROM deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and ( flow IN (${flow} ) )"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center>Flows Grouped by <span style='font-family: monospace; color: yellow'>${annotation}</span> Annotation Value</center></h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(ingressBytes) ingressBytes\nFROM \"deltafi\".\"deltafiles\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( annotations['${annotation}'] IN (${subflow}))",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || ' ' || subflow AS subflow, bytes \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['${annotation}'] AS subflow, sum(ingressBytes) AS bytes \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow}))\nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(files) ingressBytes\nFROM \"deltafi\".\"deltafiles\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( annotations['${annotation}'] IN (${subflow}))",
     "selectedFormat": 4
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flow, if(empty(subflow),'(none)',subflow) AS subflow, value\nFROM(\nSELECT flow, annotations['${annotation}'] AS subflow, sum(ingressBytes) value \nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow}))  \nGROUP BY flow, subflow\nORDER BY value DESC\nLIMIT 10)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flow, if(empty(subflow),'(none)',subflow) AS subflow, value\nFROM(\nSELECT flow, annotations['${annotation}'] AS subflow, sum(files) value \nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow}))  \nGROUP BY flow, subflow\nORDER BY value DESC\nLIMIT 10)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "DeltaFiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || ' ' || subflow AS subflow, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['${annotation}'] AS subflow, sum(files) AS values \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow}))\nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "title": "Egressed DeltaFiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || ' ' || subflow AS subflow, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['${annotation}'] AS subflow, sum(egressed) AS values \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow})) \nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "title": "Errored DeltaFiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || ' ' || subflow AS subflow, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['${annotation}'] AS subflow, sum(errored) AS values \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow})) \nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "title": "Filtered DeltaFiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || ' ' || subflow AS subflow, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['${annotation}'] AS subflow, sum(filtered) AS values \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) AND ( subflow IN (${subflow})) \nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT flow, annotations['${annotation}'] AS ${annotation}, sum(ingressBytes) as values\nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and (flow IN (${flow})) AND ( ${annotation} IN (${subflow})) \nGROUP BY flow, ${annotation}\nORDER BY values DESC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "DeltaFiles",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT flow, annotations['${annotation}'] AS ${annotation}, sum(files) as files\nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND (flow IN (${flow})) AND ( ${annotation} IN (${subflow})) \nGROUP BY flow, ${annotation}\nORDER BY files DESC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}