{
 "title": "Clickhouse Flow/Subflow",
 "tags": [
  "DeltaFi",
  "Clickhouse",
  "PROTOTYPE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "clickhouseDatasource", "label": "Clickhouse Datasource", "query": "grafana-clickhouse-datasource" },
   {
    "name": "flow",
    "label": "Flow",
    "query": "SELECT DISTINCT flow FROM deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )"
   }
  ]
 },
 "panels": [
  { "title": "Flow and Subflow Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes In (Clickhouse)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(ingressBytes) ingressBytes FROM deltafi.\"deltafiles\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Bytes In (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || ' ' || subflow AS subflow, bytes \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['subflow'] AS subflow, sum(ingressBytes) AS bytes \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) )\nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "title": "Files In (Clickhouse)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(files) ingressBytes FROM \"deltafi\".\"deltafiles\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flow, annotations['subflow'] AS subflow, sum(ingressBytes) value \nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) \nGROUP BY flow, subflow\nORDER BY value DESC\nLIMIT 10",
     "selectedFormat": 4
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flow, annotations['subflow'] AS subflow, sum(files) value \nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) \nGROUP BY flow, subflow\nORDER BY value DESC\nLIMIT 10",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Files In (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, flow || '-' || subflow AS subflow, files \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, flow, annotations['subflow'] AS subflow, sum(files) AS files \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) )\nGROUP BY flow, subflow, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "title": "Files Filtered (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(filtered) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Files Egressed (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(egressed) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Files Errored (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(errored) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT flow, annotations['subflow'] AS subflow, sum(ingressBytes) as values\nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY flow, subflow\nORDER BY values DESC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Files",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT flow, annotations['subflow'] AS subflow, sum(files) as files\nFROM \"deltafi\".\"deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\nGROUP BY flow, subflow\nORDER BY files DESC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}