{
 "title": "Clickhouse Metrics",
 "tags": [
  "DeltaFi",
  "Clickhouse"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "clickhouseDatasource", "label": "Clickhouse Datasource", "query": "grafana-clickhouse-datasource" },
   { "name": "datasource", "label": "Graphite Data Source", "query": "graphite" },
   {
    "name": "flow",
    "label": "Flow",
    "query": "SELECT DISTINCT flow FROM deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )"
   }
  ]
 },
 "panels": [
  { "title": "Clickhouse Ingress/Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes In (Clickhouse)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(ingressBytes) ingressBytes FROM \"deltafi\".\"deltafiles\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Bytes In (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(ingressBytes) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) )\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Files In (Clickhouse)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(files) ingressBytes FROM \"deltafi\".\"deltafiles\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flow, sum(ingressBytes) ingressBytes FROM \"deltafi\".\"deltafiles\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) GROUP BY flow LIMIT 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT flow, sum(files) FROM \"deltafi\".\"deltafiles\" WHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) ) GROUP BY flow ORDER BY flow ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "Files In (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(files) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( flow IN (${flow} ) )\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Files Filtered (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(filtered) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND (flow IN (${flow}))\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Files Egressed (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(egressed) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND (flow IN (${flow}))\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  {
   "title": "Files Errored (Clickhouse)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, flow, sum(errored) \" \" \nFROM deltafi.\"deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND (flow IN (${flow}))\nGROUP BY flow, time \nORDER BY time ASC WITH FILL STEP $__interval_s"
    }
   ]
  },
  { "title": "Ingress/Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Bytes In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sum(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), '1d', 'sum', false))"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Total Files In",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "sum(summarize(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), '1d', 'sum', false))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "maximumAbove(limit(sortByTotal(aliasByTags(groupByTags(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), '1d', 'sum', false), 'sum', 'ingressFlow'), 'ingressFlow')), 10), 0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'ingressFlow=~${flow:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_out', 'action=egress', 'ingressFlow=~${flow:regex}')), 'Egress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_filtered', 'ingressFlow=~${flow:regex}')), 'Filtered')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_dropped', 'ingressFlow=~${flow:regex}')), 'Dropped')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_errored', 'ingressFlow=~${flow:regex}')), 'Errored')"
    }
   ]
  },
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 5, "y": 34 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), 'average', 'ingressFlow'), '1min', 'sum', 'minutes'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Filtered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_filtered', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), '1min', 'sum', 'minutes'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_dropped', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), '1min', 'sum', 'minutes'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Errored",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_errored', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), '1min', 'sum', 'minutes'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Retried",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(smartSummarize(groupByTags(seriesByTag('name=stats_counts.files_auto_resumed', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), '1min', 'sum', 'minutes'), 'ingressFlow'), true, false)"
    }
   ]
  },
  { "title": "DeltaFile Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "target": "alias(gauge.deltafile.all.count, 'Total DeltaFiles')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "gauge.deltafile.all.count" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "gauge.deltafile.all.referencedBytes"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(gauge.deltafile.all.referencedBytes, 'Total')"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlight.count, 'In Flight')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlight.count, 'Files in flight')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "gauge.deltafile.inFlight.referencedBytes"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlight.referencedBytes, 'In Flight')"
    }
   ]
  }
 ]
}