{
 "title": "Data Source by Annotation",
 "description": "Data Source metrics grouped by the values in an annotation applied to the data sources",
 "tags": [
  "DeltaFi",
  "Clickhouse",
  "Analytics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "clickhouseDatasource", "label": "Clickhouse Datasource", "query": "grafana-clickhouse-datasource" },
   {
    "name": "dataSource",
    "label": "Data Source",
    "query": "SELECT DISTINCT dataSource FROM complete_deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )"
   },
   {
    "name": "annotation",
    "label": "Annotation",
    "query": "SELECT DISTINCT arrayJoin(mapKeys(annotations)) AS keys FROM complete_deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and ( dataSource IN (${dataSource} ) )"
   },
   {
    "name": "annotationValue",
    "label": "Annotation Value",
    "query": "SELECT DISTINCT annotations['${annotation}'] AS annotationValue FROM complete_deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and ( dataSource IN (${dataSource} ) )"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(ingressBytes)\nFROM \"deltafi\".\"complete_deltafiles\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotations['${annotation}'] IN (${annotationValue}))\nUNION ALL\nSELECT sum(ingressBytes)\nFROM \"deltafi\".\"errors\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotations['${annotation}'] IN (${annotationValue}))\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<h1><center>Data Sources Grouped by <span style='font-family: monospace; color: yellow'>${annotation}</span></center></h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(files) as files\nFROM \"deltafi\".\"complete_deltafiles\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotations['${annotation}'] IN (${annotationValue}))\nUNION ALL \nSELECT count() as files\nFROM \"deltafi\".\"errors\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotations['${annotation}'] IN (${annotationValue}))\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource || ' (' || if(empty(annotationValue),'None',annotationValue) || ')' AS annotationValue, bytes \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, sum(ingressBytes) AS bytes \nFROM deltafi.\"complete_deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue}))\nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, if(empty(annotationValue),'(none)',annotationValue) AS annotationValue, value\nFROM(\nSELECT dataSource, annotations['${annotation}'] AS annotationValue, sum(ingressBytes) value \nFROM \"deltafi\".\"complete_deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue}))  \nGROUP BY dataSource, annotationValue\nORDER BY value DESC\nLIMIT 10)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, if(empty(annotationValue),'(none)',annotationValue) AS annotationValue, value\nFROM(\nSELECT dataSource, annotations['${annotation}'] AS annotationValue, sum(files) value \nFROM \"deltafi\".\"complete_deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue}))  \nGROUP BY dataSource, annotationValue\nORDER BY value DESC\nLIMIT 10)",
     "selectedFormat": 4
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource || ' (' || if(empty(annotationValue),'None',annotationValue) || ')' AS annotationValue, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, sum(files) AS values \nFROM deltafi.\"complete_deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue}))\nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 }, "options": { "content": "<hr/>" } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 1, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 99 }
   ]
  },
  {
   "title": "Egressed DeltaFiles",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource || ' ' || annotationValue AS annotationValue, values \" \" FROM\n(SELECT dataSource, annotations['${annotation}'] AS annotationValue, sum(egressedFiles) AS values \nFROM deltafi.\"complete_deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue})) \nGROUP BY dataSource, annotationValue)\nWHERE values > 0"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource || ' (' || if(empty(annotationValue),'None',annotationValue) || ')' AS annotationValue, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, sum(egressedFiles) AS values \nFROM deltafi.\"complete_deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue})) \nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 1, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 100 }
   ]
  },
  {
   "title": "Errored DeltaFiles",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource || ' ' || annotationValue AS annotationValue, values \" \" FROM\n(SELECT dataSource, annotations['${annotation}'] AS annotationValue, count() AS values \nFROM deltafi.\"errors\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue})) \nGROUP BY dataSource, annotationValue)\nWHERE values > 0"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource || ' (' || if(empty(annotationValue),'None',annotationValue) || ')' AS annotationValue, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, count() AS values \nFROM deltafi.\"errors\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue})) \nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 1, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 101 }
   ]
  },
  {
   "title": "Filtered DeltaFiles",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource || ' ' || annotationValue AS annotationValue, values \" \" FROM\n(SELECT dataSource, annotations['${annotation}'] AS annotationValue, sum(filteredFiles) AS values \nFROM deltafi.\"complete_deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue})) \nGROUP BY dataSource, annotationValue)\nWHERE values > 0"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource || ' (' || if(empty(annotationValue),'None',annotationValue) || ')' AS annotationValue, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, sum(filteredFiles) AS values \nFROM deltafi.\"complete_deltafiles\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dataSource} ) ) AND ( annotationValue IN (${annotationValue})) \nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Bytes Ingressed",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, annotations['${annotation}'] AS tag, sum(ingressBytes) as values\nFROM \"deltafi\".\"complete_deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and (dataSource IN (${dataSource})) AND ( tag IN (${annotationValue})) \nGROUP BY dataSource, tag\nORDER BY values DESC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "DeltaFiles Processed",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT dataSource, annotations['${annotation}'] AS annotation, sum(files) as files\nFROM \"deltafi\".\"complete_deltafiles\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND (dataSource IN (${dataSource})) AND ( annotation IN (${annotationValue})) \nGROUP BY dataSource, annotation\nORDER BY files DESC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}