{
 "title": "Data Source Summary",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Graphite Data", "query": "graphite" },
   {
    "name": "dfDataSource",
    "label": "Data Source",
    "query": {}
   },
   {
    "name": "egressFlow",
    "label": "Egress",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2>Data Source Summary: ${dfDataSource}</h2></center>"
   }
  },
  { "title": "Aggregate summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}'), '1d', 'sum', false)), 'Egress')"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.bytes_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}')), 'Egress')"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}'), '1d', 'sum', false)), 'Egress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_filtered', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Filtered')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_dropped', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Dropped')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_errored', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Errored')"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}')), 'Egress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_dropped', 'dataSource=~${dfDataSource:regex}')), 'Dropped')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_errored', 'dataSource=~${dfDataSource:regex}')), 'Errored')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_filtered', 'dataSource=~${dfDataSource:regex}')), 'Filtered')"
    }
   ]
  },
  {
   "title": "Activity Heatmap by Data Source",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), 'dataSource')"
    }
   ]
  },
  { "title": "${dfDataSource} summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }, "repeat": "dfDataSource" },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}'), '1d', 'sum', false)), 'Egress')"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.bytes_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}')), 'Egress')"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}'), '1d', 'sum', false)), 'Egress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_filtered', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Filtered')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_dropped', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Dropped')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_errored', 'dataSource=~${dfDataSource:regex}'), '1d', 'sum', false)), 'Errored')"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'dataSource=~${dfDataSource:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_out', 'action=egress', 'dataSource=~${dfDataSource:regex}', 'egressFlow=~${egressdfDataSource:regex}')), 'Egress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_filtered', 'dataSource=~${dfDataSource:regex}')), 'Filtered')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_dropped', 'dataSource=~${dfDataSource:regex}')), 'Dropped')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_errored', 'dataSource=~${dfDataSource:regex}')), 'Errored')"
    }
   ]
  }
 ]
}