{
 "title": "Diagnostic",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "graphite" },
   { "name": "flow", "label": "Flow", "query": "tag_values(ingressFlow)" }
  ]
 },
 "panels": [
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), 'average', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_out', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_out', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Average Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(removeEmptySeries(aliasByTags(groupByTags(seriesByTag('name=~stats_counts.execution_time_ms', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow')), #A), 0)",
     "targetFull": "aliasByNode(divideSeriesLists(removeEmptySeries(aliasByTags(groupByTags(seriesByTag('name=~stats_counts.execution_time_ms', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow')), aliasByTags(removeEmptySeries(groupByTags(seriesByTag('name=~stats_counts.files_out', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow')), 'ingressFlow')), 0)"
    },
    {
     "target": "alias(divideSeriesLists(removeEmptySeries(alias(sum(seriesByTag('name=~stats_counts.execution_time_ms')), 'exec')), #C), 'overall')",
     "targetFull": "alias(divideSeriesLists(removeEmptySeries(alias(sum(seriesByTag('name=~stats_counts.execution_time_ms')), 'exec')), alias(removeEmptySeries(sum(seriesByTag('name=~stats_counts.files_out'))), 'files')), 'overall')"
    }
   ]
  },
  {
   "title": "Action Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_in', 'action!=ingress'), 'sum', 'source'), 'source')"
    }
   ]
  },
  {
   "title": "Disk utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.disk.usage'), 'hostname'), true, true)"
    }
   ]
  },
  {
   "title": "Action Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'))"
    }
   ]
  }
 ]
}