{
 "title": "Error Analysis",
 "description": "Error analysis by data source and annotation",
 "tags": [
  "DeltaFi",
  "Data Flow",
  "Analytics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "grafana-postgresql-datasource" },
   {
    "name": "datasources",
    "label": "Data Sources",
    "query": "WITH all_sources AS (\n  SELECT DISTINCT data_source FROM ts_ingresses WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT data_source FROM ts_egresses WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT data_source FROM ts_errors WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT data_source FROM ts_filters WHERE $__timeFilter(timestamp)\n),\ndistinct_sources AS (\n  SELECT DISTINCT data_source\n  FROM all_sources\n  WHERE data_source IS NOT NULL AND data_source != ''\n)\nSELECT data_source\nFROM (\n  SELECT data_source FROM distinct_sources\n  UNION ALL\n  SELECT 'No Datasources' WHERE NOT EXISTS (SELECT 1 FROM distinct_sources)\n) subquery\nORDER BY \n  CASE \n    WHEN data_source = 'No Datasources' THEN 0 \n    ELSE 1 \n  END,\n  data_source"
   },
   {
    "name": "annotation_key",
    "label": "Annotation Key",
    "query": "WITH all_keys AS (\n  SELECT DISTINCT jsonb_object_keys(annotations) AS key FROM ts_ingresses WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT jsonb_object_keys(annotations) AS key FROM ts_egresses WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT jsonb_object_keys(annotations) AS key FROM ts_errors WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT jsonb_object_keys(annotations) AS key FROM ts_filters WHERE $__timeFilter(timestamp)\n),\ndistinct_keys AS (\n  SELECT DISTINCT key\n  FROM all_keys\n)\nSELECT key\nFROM (\n  SELECT key FROM distinct_keys\n  UNION ALL\n  SELECT 'No Annotations' AS key\n) subquery\nWHERE \n  key = 'No Annotations' AND NOT EXISTS (SELECT 1 FROM distinct_keys)\n  OR\n  key != 'No Annotations'\nORDER BY \n  CASE WHEN key = 'No Annotations' THEN 0 ELSE 1 END,\n  key"
   },
   {
    "name": "annotation_value",
    "label": "Annotation Value",
    "query": "WITH all_values AS (\n  SELECT DISTINCT annotations->>'$annotation_key' AS value\n  FROM ts_ingresses\n  WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT annotations->>'$annotation_key' AS value\n  FROM ts_egresses\n  WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT annotations->>'$annotation_key' AS value\n  FROM ts_errors\n  WHERE $__timeFilter(timestamp)\n  UNION ALL\n  SELECT DISTINCT annotations->>'$annotation_key' AS value\n  FROM ts_filters\n  WHERE $__timeFilter(timestamp)\n),\ndistinct_values AS (\n  SELECT DISTINCT value\n  FROM all_values\n  WHERE value IS NOT NULL\n)\nSELECT value\nFROM (\n  SELECT value FROM distinct_values\n  UNION ALL\n  SELECT 'Not Present'\n) subquery\nORDER BY \n  CASE \n    WHEN value = 'Not Present' THEN 1\n    ELSE 0 \n  END,\n  value"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<h1><center>Error Analysis by <span style='font-family: monospace; color: yellow'>${annotation_key}</span></center></h1>"
   }
  },
  { "title": "File Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Errored Files",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT\n    $__from::bigint AS start_time_ms,\n    $__to::bigint AS end_time_ms,\n    $__interval_ms::bigint AS interval_ms\n),\ndata AS (\n  SELECT\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      timestamp\n    ) AS time,\n    data_source,\n    COUNT(*) AS files\n  FROM ts_errors\n  WHERE\n    timestamp >= to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    AND timestamp < to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    AND data_source IN ($datasources)\n    AND (\n      (annotations ? '$annotation_key' AND (annotations->>'$annotation_key') IN ($annotation_value))\n      OR \n      ('Not Present' IN ($annotation_value) AND NOT annotations ? '$annotation_key')\n    )\n  GROUP BY 1, 2\n),\ntime_series AS (\n  SELECT generate_series(\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    ),\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    ),\n    (SELECT (interval_ms || ' milliseconds')::interval FROM params)\n  ) AS time\n),\nall_series AS (\n  SELECT DISTINCT data_source FROM data\n),\nall_combinations AS (\n  SELECT time, data_source\n  FROM time_series\n  CROSS JOIN all_series\n)\nSELECT\n  ac.time,\n  COALESCE(SUM(d.files),0) AS errors\nFROM all_combinations ac\nLEFT JOIN data d ON ac.time = d.time AND ac.data_source = d.data_source\nGROUP BY 1\nORDER BY ac.time\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 142 }
   ]
  },
  {
   "title": "Errored Files By $annotation_key",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT\n    $__from::bigint AS start_time_ms,\n    $__to::bigint AS end_time_ms,\n    $__interval_ms::bigint AS interval_ms\n),\ndata AS (\n  SELECT\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      timestamp\n    ) AS time,\n    data_source || ' (' || COALESCE(annotations->>'$annotation_key', 'Not Present') || ')' AS series_name,\n    COUNT(*) AS files\n  FROM ts_errors\n  WHERE\n    timestamp >= to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    AND timestamp < to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    AND data_source IN ($datasources)\n    AND (\n      (annotations ? '$annotation_key' AND (annotations->>'$annotation_key') IN ($annotation_value))\n      OR \n      ('Not Present' IN ($annotation_value) AND NOT annotations ? '$annotation_key')\n    )\n  GROUP BY 1, 2\n),\ntime_series AS (\n  SELECT generate_series(\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    ),\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    ),\n    (SELECT (interval_ms || ' milliseconds')::interval FROM params)\n  ) AS time\n),\nall_series AS (\n  SELECT DISTINCT series_name FROM data\n),\nall_combinations AS (\n  SELECT time, series_name\n  FROM time_series\n  CROSS JOIN all_series\n)\nSELECT\n  ac.time,\n  ac.series_name,\n  COALESCE(d.files,0) AS files\nFROM all_combinations ac\nLEFT JOIN data d ON ac.time = d.time AND ac.series_name = d.series_name\nORDER BY ac.time, ac.series_name"
    }
   ]
  },
  {
   "title": "Errored Files by Data Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT\n    $__from::bigint AS start_time_ms,\n    $__to::bigint AS end_time_ms,\n    $__interval_ms::bigint AS interval_ms\n),\ndata AS (\n  SELECT\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      timestamp\n    ) AS time,\n    data_source,\n    COUNT(*) AS files\n  FROM ts_errors\n  WHERE\n    timestamp >= to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    AND timestamp < to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    AND data_source IN ($datasources)\n    AND (\n      (annotations ? '$annotation_key' AND (annotations->>'$annotation_key') IN ($annotation_value))\n      OR \n      ('Not Present' IN ($annotation_value) AND NOT annotations ? '$annotation_key')\n    )\n  GROUP BY 1, 2\n),\ntime_series AS (\n  SELECT generate_series(\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    ),\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    ),\n    (SELECT (interval_ms || ' milliseconds')::interval FROM params)\n  ) AS time\n),\nall_series AS (\n  SELECT DISTINCT data_source FROM data\n),\nall_combinations AS (\n  SELECT time, data_source\n  FROM time_series\n  CROSS JOIN all_series\n)\nSELECT\n  ac.time,\n  ac.data_source,\n  COALESCE(d.files,0) AS files\nFROM all_combinations ac\nLEFT JOIN data d ON ac.time = d.time AND ac.data_source = d.data_source\nORDER BY ac.time, ac.data_source"
    }
   ]
  },
  {
   "title": "Errored Files By Cause",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH params AS (\n  SELECT\n    $__from::bigint AS start_time_ms,\n    $__to::bigint AS end_time_ms,\n    $__interval_ms::bigint AS interval_ms\n),\ndata AS (\n  SELECT\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      timestamp\n    ) AS time,\n    COALESCE(cause, 'None Given') AS series_name,\n    COUNT(*) AS files\n  FROM ts_errors\n  WHERE\n    timestamp >= to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    AND timestamp < to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    AND data_source IN ($datasources)\n    AND (\n      (annotations ? '$annotation_key' AND (annotations->>'$annotation_key') IN ($annotation_value))\n      OR \n      ('Not Present' IN ($annotation_value) AND NOT annotations ? '$annotation_key')\n    )\n  GROUP BY 1, 2\n),\ntime_series AS (\n  SELECT generate_series(\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT start_time_ms FROM params) / 1000)\n    ),\n    time_bucket(\n      (SELECT (interval_ms || ' milliseconds')::interval FROM params),\n      to_timestamp((SELECT end_time_ms FROM params) / 1000)\n    ),\n    (SELECT (interval_ms || ' milliseconds')::interval FROM params)\n  ) AS time\n),\nall_series AS (\n  SELECT DISTINCT series_name FROM data\n),\nall_combinations AS (\n  SELECT time, series_name\n  FROM time_series\n  CROSS JOIN all_series\n)\nSELECT\n  ac.time,\n  ac.series_name,\n  COALESCE(d.files,0) AS files\nFROM all_combinations ac\nLEFT JOIN data d ON ac.time = d.time AND ac.series_name = d.series_name\nORDER BY ac.time, ac.series_name"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Causes by Data Source",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\ndata_source,\nSUM(causes) AS causes\nFROM\n(SELECT\ndata_source, \nCOALESCE(annotations->>'$annotation_key', 'Not Present') AS key,\nCOUNT(DISTINCT cause) AS causes\nFROM ts_errors \nWHERE\n$__timeFilter(timestamp)\nAND\ndata_source IN ($datasources)\nAND\nCOALESCE(annotations->>'$annotation_key', 'Not Present') IN ($annotation_value) \nGROUP BY 1,2\nORDER BY 1,2)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "$annotation_key  Values by Data Source",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\ndata_source,\nCOUNT(DISTINCT key) as keys\nFROM\n(SELECT\ndata_source, \nCOALESCE(annotations->>'$annotation_key', 'Not Present') AS key,\nCOUNT(DISTINCT cause) AS causes\nFROM ts_errors \nWHERE\n$__timeFilter(timestamp)\nAND\ndata_source IN ($datasources)\nAND\nCOALESCE(annotations->>'$annotation_key', 'Not Present') IN ($annotation_value) \nGROUP BY 1,2\nORDER BY 1,2)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cause frequency by Data Source",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\ndata_source, \ncause,\ncount(*) as frequency\nFROM ts_errors \nWHERE\n$__timeFilter(timestamp)\nAND\ndata_source IN ($datasources)\nAND\nCOALESCE(annotations->>'$annotation_key', 'Not Present') IN ($annotation_value) \nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "$annotation_key Value Error Frequency by Data Source",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "rawSql": "SELECT\ndata_source, \nCOALESCE(annotations->>'$annotation_key', 'Not Present') as annotation_value,\ncount(*) as frequency\nFROM ts_errors \nWHERE\n$__timeFilter(timestamp)\nAND\ndata_source IN ($datasources)\nAND\nCOALESCE(annotations->>'$annotation_key', 'Not Present') IN ($annotation_value) \nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  }
 ]
}