{
 "title": "Error Analytics",
 "description": "Error analytics for DeltaFi data sources",
 "tags": [
  "DeltaFi",
  "Clickhouse",
  "Analytics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "clickhouseDatasource", "label": "Clickhouse Datasource", "query": "grafana-clickhouse-datasource" },
   {
    "name": "dfDatasource",
    "label": "Data Source",
    "query": "SELECT DISTINCT dataSource FROM errors WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) UNION ALL SELECT DISTINCT dataSource FROM complete_deltafiles WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime )"
   },
   {
    "name": "annotation",
    "label": "Annotation",
    "query": "SELECT DISTINCT arrayJoin(mapKeys(annotations)) AS keys FROM errors WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and ( dataSource IN (${dfDatasource} ) )"
   },
   {
    "name": "annotationValue",
    "label": "Annotation Value",
    "query": "SELECT DISTINCT annotations['${annotation}'] AS annotationValue FROM errors WHERE $__timeFilter(timestamp) AND ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and ( dataSource IN (${dfDatasource} ) )"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count()\nFROM \"deltafi\".\"errors\"\nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dfDatasource} ) ) AND ( annotations['${annotation}'] IN (${annotationValue}))"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "targets": [
    {
     "rawSql": "SELECT time, sum(values) \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, count() as values \nFROM deltafi.\"errors\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dfDatasource} ) ) AND ( annotationValue IN (${annotationValue}))\nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s) GROUP BY time"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, ' [' || if(empty(annotationValue),'none',annotationValue) || ']' AS annotationValue, value\nFROM(\nSELECT dataSource, annotations['${annotation}'] AS annotationValue, count() value \nFROM \"deltafi\".\"errors\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dfDatasource} ) ) AND ( annotationValue IN (${annotationValue}))  \nGROUP BY dataSource, annotationValue\nORDER BY value DESC\nLIMIT 500)"
    }
   ]
  },
  {
   "title": "Errors by ${annotation}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource || ' [' || if(empty(annotationValue),'none',annotationValue) || ']' AS annotationValue, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, count() AS values \nFROM deltafi.\"errors\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dfDatasource} ) ) AND ( annotationValue IN (${annotationValue}))\nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dataSource,  sum(value)\nFROM(\nSELECT dataSource, annotations['${annotation}'] AS annotationValue, count() value \nFROM \"deltafi\".\"errors\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dfDatasource} ) ) AND ( annotationValue IN (${annotationValue}))  \nGROUP BY dataSource, annotationValue\nORDER BY value DESC\nLIMIT 500) GROUP BY dataSource"
    }
   ]
  },
  {
   "title": "Errors by Data Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "targets": [
    {
     "rawSql": "SELECT time, dataSource, values \" \" FROM\n(SELECT $__timeInterval(timestamp) as time, dataSource, annotations['${annotation}'] AS annotationValue, count() AS values \nFROM deltafi.\"errors\" \nWHERE $__timeFilter(timestamp) AND   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) AND ( dataSource IN (${dfDatasource} ) ) AND ( annotationValue IN (${annotationValue}))\nGROUP BY dataSource, annotationValue, time \nORDER BY time ASC WITH FILL STEP $__interval_s)"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "options": { "content": "<hr/>" } },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Causes of Errors by Data Source",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, count(cause) FROM (SELECT dataSource, annotations['${annotation}'] AS tag, cause, count() as values\nFROM \"deltafi\".\"errors\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and (dataSource IN (${dfDatasource})) AND ( tag IN (${annotationValue})) \nGROUP BY dataSource, cause, tag\nORDER BY values DESC) GROUP BY dataSource"
    }
   ]
  },
  {
   "title": "Count of ${annotation} by Data Source",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, count(tag) as \"Unique ${annotation} values\" FROM (SELECT dataSource, annotations['${annotation}'] AS tag, count() as values\nFROM \"deltafi\".\"errors\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and (dataSource IN (${dfDatasource})) AND ( tag IN (${annotationValue})) \nGROUP BY dataSource, tag\nORDER BY values DESC) GROUP BY dataSource"
    }
   ]
  },
  {
   "title": "Errors by Cause",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, cause, sum(values) FROM (SELECT dataSource, annotations['${annotation}'] AS tag, cause, count() as values\nFROM \"deltafi\".\"errors\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and (dataSource IN (${dfDatasource})) AND ( tag IN (${annotationValue})) \nGROUP BY dataSource, cause, tag\nORDER BY values DESC) GROUP BY dataSource, cause"
    }
   ]
  },
  {
   "title": "Errors by ${annotation} Value",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT dataSource, tag as \"value\", sum(values) FROM (SELECT dataSource, annotations['${annotation}'] AS tag, cause, count() as values\nFROM \"deltafi\".\"errors\" \nWHERE   ( timestamp  >= $__fromTime AND timestamp <= $__toTime ) and (dataSource IN (${dfDatasource})) AND ( tag IN (${annotationValue})) \nGROUP BY dataSource, cause, tag\nORDER BY values DESC) GROUP BY dataSource, tag"
    }
   ]
  }
 ]
}