{
 "title": "Flow Status",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Errors (Last hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": " Errors" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(nonNegativeDerivative(movingSum(seriesByTag('name=files_errored', 'metricattribute=count'), '1hour')), 'sum', 'ingressFlow'), 'ingressFlow')"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByTags(perSecond(scale(seriesByTag('name=bytes_in', 'metricattribute=count', 'source=ingress'), 8)), 'ingressFlow'), 'max', true)"
    }
   ]
  },
  {
   "title": "Ingress Bit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(perSecond(sum(seriesByTag('name=bytes_in', 'metricattribute=count', 'source=ingress'))), 8), 'bitrate')"
    }
   ]
  },
  {
   "title": "Egress Bit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(perSecond(sum(seriesByTag('name=bytes_out', 'metricattribute=count', 'action=egress'))), 8), 'bitrate')"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(nonNegativeDerivative(groupByTags(seriesByTag('name=bytes_in', 'metricattribute=count', 'action=IngressAction'), 'sum', 'ingressFlow')), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=bytes_out', 'metricattribute=count')), 'averageSeries', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=files_in', 'metricattribute=count', 'action=IngressAction')), 'average', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=files_out', 'metricattribute=count')), 'averageSeries', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Action Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=files_in', 'metricattribute=count', 'source!=ingress')), 'average', 'source'), 'source'))"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortBy(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'), 'max', true)"
    }
   ]
  },
  {
   "title": "Action Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'))"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.disk'), 'hostname', 'name'), true, true)"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(keepLastValue(seriesByTag('name=~gauge.node.disk'), inf), 'hostname', 'name'), true, true)"
    }
   ]
  }
 ]
}