{
 "title": "Ingress/Egress",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ingress bps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(aggregate(groupByTags(scale(seriesByTag('name=bytes_in', 'action=IngressAction', 'source=ingress', 'metricattribute=count'),8), 'sum', 'ingressFlow'), 'sum'))"
    }
   ]
  },
  {
   "title": "Ingress Files",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(aggregate(groupByTags(seriesByTag('name=files_in', 'action=IngressAction', 'source=ingress', 'metricattribute=count'), 'sum', 'ingressFlow'), 'sum'))"
    }
   ]
  },
  {
   "title": " Last Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "movingSum(aggregate(nonNegativeDerivative(seriesByTag('name=bytes_out', 'metricattribute=count')), 'sum'), '1min')"
    }
   ]
  },
  {
   "title": "Egress bps",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(aggregate(groupByTags(scale(seriesByTag('name=bytes_out', 'metricattribute=count'),8), 'sum', 'ingressFlow'), 'sum'))"
    }
   ]
  },
  {
   "title": "Egress Files",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "perSecond(aggregate(groupByTags(seriesByTag('name=files_out', 'metricattribute=count'), 'sum', 'ingressFlow'), 'sum'))"
    }
   ]
  },
  {
   "title": "Ingress Bit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(perSecond(sum(seriesByTag('name=bytes_in', 'metricattribute=count', 'source=ingress'))), 8), 'bitrate')"
    }
   ]
  },
  {
   "title": "Egress Bit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scale(perSecond(sum(seriesByTag('name=bytes_out', 'metricattribute=count', 'action=egress'))), 8), 'bitrate')"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(nonNegativeDerivative(groupByTags(seriesByTag('name=bytes_in', 'metricattribute=count', 'action=IngressAction'), 'sum', 'ingressFlow')), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=bytes_out', 'metricattribute=count')), 'averageSeries', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=files_in', 'metricattribute=count', 'action=IngressAction')), 'average', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=files_out', 'metricattribute=count')), 'averageSeries', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  }
 ]
}