{
 "title": "Application Log Viewer",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging",
  "DeltaFi"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" },
   {
    "name": "container_name",
    "label": "App",
    "query": "label_values({app=~\".+\"}, app)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values({app=\"$container_name\"}, pod)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({app=\"$container_name\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "error" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$container_name\", pod=~\"$pod_name\", stream=~\"$stream\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$container_name\", stream=~\"$stream\", pod=~\"$pod_name\"} |~ `(?i)$searchable_pattern` [$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{app=\"$container_name\", pod=~\"$pod_name\", stream=~\"$stream\"} |~ `(?i)$searchable_pattern`"
    }
   ]
  }
 ]
}