{
 "title": "Processing Report",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1w/w", "to": "now-1w/w" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h2>DeltaFi System Processing Report</h2>\n  <div style=\"margin-top:-10px\">${__from:date:YYYY-MM-DD} to ${__to:date:YYYY-MM-DD}</div>\n</center>\n"
   }
  },
  {
   "title": "Total Flows",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(countSeries(seriesByTag('action=ingress', 'name=stats_counts.files_in')), 'Flows')"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_out', 'action=egress'), '1d', 'sum', false)), 'Egress')"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_in', 'action=ingress'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_out', 'action=egress'), '1d', 'sum', false)), 'Egress')"
    }
   ]
  },
  {
   "title": "Aggregate Processed Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_in', 'action=ingress')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_out', 'action=egress')), 'Egress')"
    }
   ]
  },
  {
   "title": "Processed Files by Flow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=stats_counts.files_in', 'action=ingress'), 'ingressFlow')"
    }
   ]
  },
  {
   "title": "Processed Bytes by Flow",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByTags(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress'), '1d', 'sum'), 'ingressFlow')"
    },
    {
     "target": "aliasByTags(summarize(seriesByTag('name=stats_counts.bytes_out', 'action=egress'), '1d', 'sum'), 'ingressFlow')"
    }
   ]
  },
  {
   "title": "Processed Files by Flow",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(summarize(seriesByTag('name=stats_counts.files_in', 'action=ingress'), '1d', 'sum'), 'ingressFlow')"
    },
    {
     "target": "aliasByTags(summarize(seriesByTag('name=stats_counts.files_out', 'action=egress'), '1d', 'sum'), 'ingressFlow')"
    }
   ]
  },
  {
   "title": "Ingressed Files by Flow",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(summarize(seriesByTag('name=stats_counts.files_in', 'action=ingress'), '1d', 'sum'), 'ingressFlow')"
    }
   ]
  }
 ]
}