{
 "title": "Survey Metrics [DEPRECATED]",
 "description": "Summary dashboard for survey metrics.  Deprecated in favor of api/v1/survey annotated metric API.",
 "tags": [
  "DeltaFi",
  "Survey"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "graphite" },
   {
    "name": "flow",
    "label": "Survey Flow",
    "query": {}
   },
   {
    "name": "direction",
    "label": "Direction",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h2>Survey Metrics: ${flow}</h2></center>"
   }
  },
  {
   "title": "Survey Flow Summary [DEPRECATED]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "filterSeries(aliasByTags(summarize(seriesByTag('name=stats_counts.survey.bytes', 'surveyFlow=~${flow:regex}', 'surveyDirection=~${direction:regex}'), '1d', 'sum', false), 'surveyFlow', 'surveyDirection'), 'sum', '>', 0)"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "filterSeries(aliasByTags(seriesByTag('name=stats_counts.survey.bytes', 'surveyFlow=~${flow:regex}', 'surveyDirection=~${direction:regex}'), 'surveyFlow', 'surveyDirection'), 'sum', '>', 0)"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "filterSeries(aliasByTags(summarize(seriesByTag('name=stats_counts.survey.files', 'surveyFlow=~${flow:regex}', 'surveyDirection=~${direction:regex}'), '1d', 'sum', false), 'surveyFlow', 'surveyDirection'), 'sum', '>', 0)"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "filterSeries(aliasByTags(seriesByTag('name=stats_counts.survey.files', 'surveyFlow=~${flow:regex}', 'surveyDirection=~${direction:regex}'), 'surveyFlow', 'surveyDirection'), 'sum', '>', 0)"
    }
   ]
  },
  { "title": "Survey Subflows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Files",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=stats_counts.survey.subflow.files', 'surveyFlow=~${flow:regex}'), 'surveySubflow', 'surveyDirection')"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByTags(summarize(seriesByTag('name=stats_counts.survey.subflow.bytes', 'surveyFlow=~${flow:regex}'), '1d', 'sum', false), 'surveySubflow', 'surveyDirection')"
    }
   ]
  }
 ]
}