{
 "title": "System Overview",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "graphite" },
   { "name": "flow", "label": "Flow", "query": "tag_values(ingressFlow)" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 16, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(scale(scaleToSeconds(sum(seriesByTag('name=stats_counts.bytes_in', 'source=ingress', 'ingressFlow=~${flow:regex}')), 1), 8), 'Ingress')"
    },
    {
     "target": "alias(scale(scaleToSeconds(sum(seriesByTag('name=stats_counts.bytes_out', 'ingressFlow=~${flow:regex}')), 1), 8), 'Egress')"
    }
   ]
  },
  {
   "title": "Ingress Flow Bitrate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(groupByTags(transformNull(scale(scaleToSeconds(seriesByTag('name=stats_counts.bytes_in', 'ingressFlow=~${flow:regex}', 'action=ingress'), 1), 8), 0), 'sum', 'ingressFlow'), 'ingressFlow'))"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Egress Flow Bitrate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByTags(groupByTags(transformNull(scale(scaleToSeconds(seriesByTag('name=stats_counts.bytes_out', 'ingressFlow=~${flow:regex}'), 1), 8), 0), 'sum', 'ingressFlow'), 'ingressFlow'))"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_out', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'ingressFlow=~${flow:regex}')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_out', 'action=egress', 'ingressFlow=~${flow:regex}')), 'Egress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_filtered', 'ingressFlow=~${flow:regex}')), 'Filtered')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_dropped', 'ingressFlow=~${flow:regex}')), 'Dropped')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_errored', 'ingressFlow=~${flow:regex}')), 'Errored')"
    }
   ]
  },
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 16 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_in', 'action=ingress', 'ingressFlow=~${flow:regex}'), 'average', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_out', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Filtered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_filtered', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Dropped",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_dropped', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "title": "Files Errored",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_errored', 'ingressFlow=~${flow:regex}'), 'sum', 'ingressFlow'), 'ingressFlow'), true, false)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<br/><center><h1>Action Activity</h1></center>"
   }
  },
  {
   "title": "Action Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(nonNegativeDerivative(seriesByTag('name=files_in', 'metricattribute=count', 'action!=ingress')), 'sum', 'source'), 'source')"
    },
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_in', 'action!=ingress'), 'sum', 'source'), 'source')"
    }
   ]
  },
  {
   "title": "Action Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "options": {
    "content": "<br/><center><h1>Disk Status</h1></center>"
   }
  },
  {
   "title": "Disk utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.disk.usage'), 'hostname'), true, true)"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "target": "aliasByTags(sortByName(seriesByTag('name=~gauge.node.disk'), true, true), 'hostname')"
    }
   ]
  }
 ]
}