{
 "title": "Data Source by Annotation",
 "description": "Data Source metrics grouped by the values in an annotation applied to the data sources",
 "tags": [
  "DeltaFi",
  "Data Flow",
  "Analytics"
 ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "label": "Database", "query": "grafana-postgresql-datasource" },
   {
    "name": "datasources",
    "label": "Data Sources",
    "query": "SELECT DISTINCT data_source\nFROM (\n    SELECT DISTINCT data_source FROM ts_ingresses \n    WHERE $__timeFilter(timestamp)\n    UNION\n    SELECT DISTINCT data_source FROM ts_egresses \n    WHERE $__timeFilter(timestamp)\n    UNION\n    SELECT DISTINCT data_source FROM ts_errors \n    WHERE $__timeFilter(timestamp)\n    UNION\n    SELECT DISTINCT data_source FROM ts_filters \n    WHERE $__timeFilter(timestamp)\n) sources\n\nORDER BY data_source;"
   },
   {
    "name": "annotation_key",
    "label": "Annotation Key",
    "query": "SELECT key\nFROM(\nSELECT DISTINCT key\nFROM ts_annotations\nUNION ALL\nSELECT 'No Annotations'\n  WHERE NOT EXISTS (\nSELECT 1\nFROM ts_annotations \nLIMIT 1\n)\n) all_keys\nORDER BY key;"
   },
   {
    "name": "annotation_value",
    "label": "Annotation Value",
    "query": "SELECT value\nFROM (\n  SELECT DISTINCT value\n  FROM ts_annotations\n  WHERE $__timeFilter(entity_timestamp)\n    AND data_source IN ($datasources)\n    AND key = '$annotation_key'\n  \n  UNION ALL\n  SELECT 'Not Present'\n) all_values\nORDER BY \n  CASE WHEN value = 'Not Present' THEN 0 ELSE 1 END,\n  value;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": "<h1><center>Data Sources Grouped by <span style='font-family: monospace; color: yellow'>${annotation_key}</span></center></h1>"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 119 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 3 },
   "options": {
    "content": "<h1><center>Ingress</center></h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 124 }
   ]
  },
  {
   "title": "Ingressed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket_gapfill(($__interval_ms || ' ms')::interval, i.timestamp) AS time,\n    i.data_source || ' (' || COALESCE(a.value, 'Not Present') || ')' AS series_name,\n    COALESCE(SUM(i.ingress_bytes), 0) AS bytes\nFROM ts_ingresses i\nLEFT JOIN ts_annotations a ON a.entity_id = i.id AND a.key = '$annotation_key'\nWHERE $__timeFilter(i.timestamp)\n  AND i.data_source IN ($datasources)\n  AND (\n    '*' IN ($annotation_value)\n   OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n   OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n    )\nGROUP BY 1, 2\nORDER BY time, series_name;"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 119 }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 124 }
   ]
  },
  {
   "title": "Ingressed Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket_gapfill(($__interval_ms || ' ms')::interval, i.timestamp) AS time,\n    i.data_source || ' (' || COALESCE(a.value, 'Not Present') || ')' AS series_name,\n    COALESCE(COUNT(*), 0) AS values\nFROM ts_ingresses i\nLEFT JOIN ts_annotations a ON a.entity_id = i.id AND a.key = '$annotation_key'\nWHERE $__timeFilter(i.timestamp)\n  AND i.data_source IN ($datasources)\n  AND (\n    '*' IN ($annotation_value)\n   OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n   OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n    )\nGROUP BY 1, 2\nORDER BY time, series_name;"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 135 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 6, "y": 24 },
   "options": {
    "content": "<h1><center>Egress</center></h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 138 }
   ]
  },
  {
   "title": "Egressed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket_gapfill(($__interval_ms || ' ms')::interval, e.timestamp) AS time,\n    e.data_source || ' (' || COALESCE(a.value, 'Not Present') || ')' AS series_name,\n    COALESCE(SUM(e.egress_bytes), 0) AS bytes\nFROM ts_egresses e\nLEFT JOIN ts_annotations a ON a.entity_id = e.id AND a.key = '$annotation_key'\nWHERE $__timeFilter(e.timestamp)\n  AND e.data_source IN ($datasources)\n  AND (\n    '*' IN ($annotation_value)\n    OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n    OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n  )\nGROUP BY 1, 2\nORDER BY time, series_name;"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 135 }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 138 }
   ]
  },
  {
   "title": "Egressed Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n    time_bucket_gapfill(($__interval_ms || ' ms')::interval, e.timestamp) AS time,\n    e.data_source || ' (' || COALESCE(a.value, 'Not Present') || ')' AS series_name,\n    COALESCE(COUNT(*), 0) AS values\nFROM ts_egresses e\n         LEFT JOIN ts_annotations a ON a.entity_id = e.id AND a.key = '$annotation_key'\nWHERE $__timeFilter(e.timestamp)\n  AND e.data_source IN ($datasources)\n  AND (\n    '*' IN ($annotation_value)\n   OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n   OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n    )\nGROUP BY 1, 2\nORDER BY time, series_name;"
    }
   ]
  },
  {
   "title": "File Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 142 }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 142 }
   ]
  },
  {
   "title": "Errored Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, e.timestamp) AS time,\n  e.data_source || ' (' || COALESCE(a.value, 'Not Present') || ')' AS series_name,\n  COALESCE(COUNT(*), 0) AS values\nFROM ts_errors e\nLEFT JOIN ts_annotations a ON a.entity_id = e.id AND a.key = '$annotation_key'\nWHERE $__timeFilter(e.timestamp)\n  AND e.data_source IN ($datasources)\n  AND (\n    '*' IN ($annotation_value)\n    OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n    OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n  )\nGROUP BY 1, 2\nORDER BY time, series_name;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 147 }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 147 }
   ]
  },
  {
   "title": "Filtered Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT \n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, f.timestamp) AS time,\n  f.data_source || ' (' || COALESCE(a.value, 'Not Present') || ')' AS series_name,\n  COALESCE(COUNT(*), 0) AS values\nFROM ts_filters f\nLEFT JOIN ts_annotations a ON a.entity_id = f.id AND a.key = '$annotation_key'\nWHERE $__timeFilter(f.timestamp)\n  AND f.data_source IN ($datasources)\n  AND (\n    '*' IN ($annotation_value)\n    OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n    OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n  )\nGROUP BY 1, 2\nORDER BY time, series_name;"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n  combined.data_source,\n  COALESCE(a.value, 'Not Present') AS annotation_value,\n  COALESCE(SUM(CASE WHEN table_name = 'ingress' THEN bytes END), 0) AS total_ingress_bytes,\n  COALESCE(SUM(CASE WHEN table_name = 'ingress' THEN 1 END), 0) AS ingress_files,\n  COALESCE(SUM(CASE WHEN table_name = 'egress' THEN bytes END), 0) AS total_egress_bytes,\n  COALESCE(SUM(CASE WHEN table_name = 'egress' THEN 1 END), 0) AS egress_files,\n  COALESCE(SUM(CASE WHEN table_name = 'error' THEN 1 END), 0) AS error_files,\n  COALESCE(SUM(CASE WHEN table_name = 'filter' THEN 1 END), 0) AS filter_files\nFROM (\n  SELECT 'ingress' as table_name, data_source, id, ingress_bytes AS bytes \n  FROM ts_ingresses \n  WHERE $__timeFilter(timestamp)\n    AND data_source IN ($datasources)\n  UNION ALL\n  SELECT 'egress' as table_name, data_source, id, egress_bytes AS bytes \n  FROM ts_egresses \n  WHERE $__timeFilter(timestamp)\n    AND data_source IN ($datasources)\n  UNION ALL\n  SELECT 'error' as table_name, data_source, id, NULL AS bytes \n  FROM ts_errors \n  WHERE $__timeFilter(timestamp)\n    AND data_source IN ($datasources)\n  UNION ALL\n  SELECT 'filter' as table_name, data_source, id, NULL AS bytes \n  FROM ts_filters \n  WHERE $__timeFilter(timestamp)\n    AND data_source IN ($datasources)\n) combined\nLEFT JOIN ts_annotations a ON a.entity_id = combined.id AND a.key = '$annotation_key'\nWHERE (\n    '*' IN ($annotation_value)\n    OR (a.value IS NOT NULL AND a.value IN ($annotation_value))\n    OR ('Not Present' IN ($annotation_value) AND a.value IS NULL)\n  )\nGROUP BY 1, 2\nORDER BY data_source, annotation_value;"
    }
   ]
  }
 ]
}