{
 "title": "Diagnostic",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Graphite Data", "query": "graphite" },
   {
    "name": "dfDataSource",
    "label": "Data Source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Files In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_from_source', 'dataSource=~${dfDataSource:regex}'), 'average', 'dataSource'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_from_source', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Files Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_to_sink', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(groupByTags(seriesByTag('name=stats_counts.bytes_to_sink', 'dataSource=~${dfDataSource:regex}'), 'sum', 'dataSource'), 'dataSource'), true, false)"
    }
   ]
  },
  {
   "title": "Action Execution Latency (Average Action Execution Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByMetric(divideSeriesLists(#A, #B))",
     "targetFull": "aliasByMetric(divideSeriesLists(aliasByTags(groupByTags(smartSummarize(seriesByTag('name=stats_counts.action_execution_time_ms'), '$__interval', 'sum', 'minutes'), 'sum', 'source'), 'source'), aliasByTags(groupByTags(smartSummarize(seriesByTag('name=stats_counts.action_execution'), '$__interval', 'sum', 'minutes'), 'sum', 'source'), 'source')))"
    },
    {
     "target": "aliasByMetric(divideSeriesLists(#D, #E))",
     "targetFull": "aliasByMetric(divideSeriesLists(alias(sum(aliasByTags(groupByTags(smartSummarize(seriesByTag('name=stats_counts.action_execution_time_ms'), '$__interval', 'sum', 'minutes'), 'sum', 'source'), 'source')), 'Overall'), alias(sum(aliasByTags(groupByTags(smartSummarize(seriesByTag('name=stats_counts.action_execution'), '$__interval', 'sum', 'minutes'), 'sum', 'source'), 'source')), 'Overall')))"
    }
   ]
  },
  {
   "title": "Action Executions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(smartSummarize(seriesByTag('name=stats_counts.action_execution'), '$__interval', 'sum', 'minutes'), 'sum', 'source'), 'source')"
    }
   ]
  },
  {
   "title": "Disk utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.disk.usage'), 'hostname', 'service'), true, true)"
    }
   ]
  },
  {
   "title": "Action Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'))"
    }
   ]
  }
 ]
}