{
 "title": "Error Analysis",
 "description": "Error analysis by data source and annotation",
 "tags": [
  "DeltaFi",
  "Data Flow",
  "Analytics"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dataSources",
    "label": "Data Sources",
    "query": "SELECT DISTINCT \n  fd.name AS __value,\n  fd.name AS __text\nFROM (\n    SELECT DISTINCT aa.data_source_id\n    FROM analytics_5m_anno aa \n    WHERE $__timeFilter(aa.bucket_start)\n    UNION\n    SELECT DISTINCT an.data_source_id\n    FROM analytics_5m_noanno an\n    WHERE $__timeFilter(an.bucket_start)\n) a\nJOIN flow_definitions fd\nON fd.id = a.data_source_id"
   },
   {
    "name": "groups",
    "label": "Groups",
    "query": "SELECT DISTINCT\n  eg.name AS __text,\n  eg.name AS __value\nFROM (\n  SELECT event_group_id, data_source_id, bucket_start\n  FROM analytics_5m_anno\n  UNION ALL\n  SELECT event_group_id, data_source_id, bucket_start\n  FROM analytics_5m_noanno\n) a\nJOIN flow_definitions fd ON a.data_source_id = fd.id\nJOIN event_groups eg ON a.event_group_id = eg.id\nWHERE $__timeFilter(a.bucket_start)\n  AND ('All' in ($dataSources) OR fd.name in ($dataSources));"
   },
   {
    "name": "annotationKey",
    "label": "Annotation Key",
    "query": "SELECT DISTINCT\n  ak.key_name AS __text,\n  ak.key_name AS __value\nFROM analytics_5m_anno aa\nJOIN flow_definitions fd ON aa.data_source_id = fd.id\nJOIN event_groups eg ON aa.event_group_id = eg.id\nJOIN annotation_keys ak ON aa.annotation_key_id = ak.id\nWHERE $__timeFilter(aa.bucket_start)\n  AND ('All' IN ($dataSources) OR fd.name IN ($dataSources))\n  AND ('All' IN ($groups) OR eg.name IN ($groups))"
   },
   {
    "name": "annotationValues",
    "label": "Annotation Values",
    "query": "SELECT DISTINCT\n  av.value_text AS __text,\n  av.value_text AS __value\nFROM analytics_5m_anno aa\nJOIN flow_definitions fd ON aa.data_source_id = fd.id\nJOIN event_groups eg ON aa.event_group_id = eg.id\nJOIN annotation_keys ak ON aa.annotation_key_id = ak.id\nJOIN annotation_values av ON aa.annotation_value_id = av.id\nWHERE $__timeFilter(aa.bucket_start)\n  AND ('All' IN ($dataSources) OR fd.name IN ($dataSources))\n  AND ('All' IN ($groups) OR eg.name IN ($groups))\n  AND ak.key_name = $annotationKey \n  AND $annotationKey != 'All'"
   },
   { "name": "database", "label": "Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "File Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errored Files",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, bucket_time) AS time,\n  COALESCE(SUM(error_files), 0) AS error_files\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  ($__interval_ms || ' ms'),\n  'ERRORS'\n)\nWHERE bucket_time >= $__timeFrom()\nAND bucket_time <= $__timeTo()\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 147 }
   ]
  },
  {
   "title": "Errored Files By Annotation Key: $annotationKey",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, bucket_time) AS time,\n  annotation_value,\n  COALESCE(SUM(error_files), 0) AS error_files\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  ($__interval_ms || ' ms'),\n  'ERRORS'\n)\nWHERE bucket_time >= $__timeFrom()\nAND bucket_time <= $__timeTo() \nGROUP BY time, annotation_value\nORDER BY time, annotation_value;"
    }
   ]
  },
  {
   "title": "Errored Files by Data Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, bucket_time) AS time,\n  datasource_name AS data_source,\n  COALESCE(SUM(error_files), 0) AS error_files\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  ($__interval_ms || ' ms'),\n  'ERRORS'\n)\nWHERE bucket_time >= $__timeFrom()\nAND bucket_time <= $__timeTo() \nGROUP BY time, datasource_name\nORDER BY time, data_source;"
    }
   ]
  },
  {
   "title": "Errored Files By Cause",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, bucket_time) AS time,\n  cause,\n  COALESCE(SUM(error_files), 0) AS error_files\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  ($__interval_ms || ' ms'),\n  'ERRORS'\n)\nWHERE bucket_time >= $__timeFrom()\nAND bucket_time <= $__timeTo() \nGROUP BY time, cause\nORDER BY time, cause;"
    }
   ]
  },
  {
   "title": "Errored Files By Group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket_gapfill(($__interval_ms || ' ms')::interval, bucket_time) AS time,\n  group_name AS event_group,\n  COALESCE(SUM(error_files), 0) AS error_files\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  ($__interval_ms || ' ms'),\n  'ERRORS'\n)\nWHERE bucket_time >= $__timeFrom()\nAND bucket_time <= $__timeTo() \nGROUP BY time, group_name\nORDER BY time, event_group;"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Cause frequency by Data Source",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  datasource_name AS data_source,\n  cause,\n  COALESCE(SUM(error_files), 0) AS frequency\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  '100 years',\n  'ERRORS'\n)\nGROUP BY datasource_name, cause\nORDER BY data_source, cause;"
    }
   ]
  },
  {
   "title": "Cause frequency by Group",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  group_name AS event_group,\n  cause,\n  COALESCE(SUM(error_files), 0) AS frequency\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  '100 years',\n  'ERRORS'\n)\nGROUP BY group_name, cause\nORDER BY event_group, cause;"
    }
   ]
  },
  {
   "title": "$annotationKey Value frequency by Data Source",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  datasource_name AS data_source,\n  annotation_value,\n  COALESCE(SUM(error_files), 0) AS frequency\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  '100 years',\n  'ERRORS'\n)\nGROUP BY datasource_name, annotation_value\nORDER BY data_source, annotation_value;"
    }
   ]
  },
  {
   "title": "$annotationKey Value Error Frequency by Group",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  group_name AS event_group,\n  annotation_value,\n  COALESCE(SUM(error_files), 0) AS frequency\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  '100 years',\n  'ERRORS'\n)\nGROUP BY group_name, annotation_value\nORDER BY event_group, annotation_value;"
    }
   ]
  },
  {
   "title": "Error Frequency by Flow and Action",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT\n  datasource_name AS flow_name,\n  action_name,\n  COALESCE(SUM(error_files), 0) AS total_errors\nFROM get_errors_filters_data(\n  $annotationKey,\n  ARRAY[$annotationValues],\n  ARRAY[$dataSources],\n  ARRAY[$groups],\n  $__timeFrom(),\n  $__timeTo(),\n  '100 years',\n  'ERRORS'\n)\nGROUP BY datasource_name, action_name\nORDER BY flow_name, action_name;"
    }
   ]
  }
 ]
}