{
 "title": "Log Overview",
 "description": "Overview of all system logging",
 "tags": [
  "Loki",
  "logging",
  "DeltaFi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" },
   {
    "name": "container_name",
    "label": "App",
    "query": "label_values({namespace=\"deltafi\"}, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "All Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=\"deltafi\", app=~\"$container_name\"} [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"deltafi\", app=~\"$container_name\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=\"deltafi\", app=~\"$container_name\"} |~ `(?i)error` [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"deltafi\", app=~\"$container_name\"} |~ `(?i)error` [$__interval]))"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=\"deltafi\", app=~\"$container_name\"} |~ `(?i)warn` [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Total Warnings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"deltafi\", app=~\"$container_name\"} |~ `(?i)warn` [$__interval]))"
    }
   ]
  },
  {
   "title": "Action Logs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum by(action) (count_over_time({namespace=\"deltafi\", action=~\".+\"} [$__interval]))",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}