{
 "title": "Processing Report",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1d/h", "to": "now-1h/h+1s" },
 "refresh": "1d",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Database", "query": "graphite" },
   {
    "name": "dataSink",
    "label": "Data Sink",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h2>DeltaFi System Processing Report</h2>\n  <div style=\"margin-top:-10px\">${__from:date:YYYY-MM-DD HH:mm} to ${__to:date:YYYY-MM-DD HH:mm}</div>\n</center>\n"
   }
  },
  {
   "title": "Total Data Sources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(countSeries(groupByTags(seriesByTag('name=stats_counts.files_from_source', 'dataSource!='), 'countSeries', 'dataSource')), 'Data Sources')"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_in', 'action=ingress'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.bytes_out', 'action=egress', 'dataSink=~${dataSink:regex}'), '1d', 'sum', false)), 'Egress')"
    }
   ]
  },
  {
   "title": "Total Files",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_from_source'), '1d', 'sum', false)), 'Ingress')"
    },
    {
     "target": "alias(sum(summarize(seriesByTag('name=stats_counts.files_to_sink', 'dataSink=~${dataSink:regex}'), '1d', 'sum', false)), 'Egress')"
    }
   ]
  },
  {
   "title": "Aggregate Processed Files",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_from_source')), 'Ingress')"
    },
    {
     "target": "alias(sum(seriesByTag('name=stats_counts.files_to_sink', 'dataSink=~${dataSink:regex}')), 'Egress')"
    }
   ]
  },
  {
   "title": "Processed Files by Flow",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_from_source', 'dataSource!='), 'sum', 'dataSource'), 'dataSource')"
    }
   ]
  },
  {
   "title": "Processed Bytes by Data Source",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByTags(summarize(seriesByTag('name=stats_counts.bytes_from_source', 'dataSource!='), '1d', 'sum'), 'dataSource'))"
    },
    {
     "target": "removeEmptySeries(aliasByTags(summarize(seriesByTag('name=stats_counts.bytes_to_sink', 'dataSource!=', 'dataSink=~${dataSink:regex}'), '1d', 'sum'), 'dataSource'))"
    }
   ]
  },
  {
   "title": "Processed Files by Data Source",
   "type": "table",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByTags(summarize(seriesByTag('name=stats_counts.files_from_source', 'dataSource!='), '1d', 'sum'), 'dataSource'))"
    },
    {
     "target": "removeEmptySeries(aliasByTags(summarize(seriesByTag('name=stats_counts.files_to_sink', 'dataSink=~${dataSink:regex}'), '1d', 'sum'), 'dataSource'))"
    }
   ]
  }
 ]
}