{
 "title": "System Performance",
 "tags": [ "DeltaFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "graphite" },
   {
    "name": "namespaces",
    "label": "Namespaces",
    "query": {}
   },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Aggregate Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlightCount, 'Files in flight')"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "alias(gauge.deltafile.inFlightCount, 'In Flight')"
    }
   ]
  },
  {
   "title": "Action Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.files_in', 'action!=ingress'), 'sum', 'source'), 'source')"
    }
   ]
  },
  {
   "title": "Action Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "sortByTotal(aliasByTags(seriesByTag('name=gauge.action_queue.queue_size'), 'queue_name'))"
    }
   ]
  },
  {
   "title": "Action Execution Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(seriesByTag('name=stats_counts.action_execution_time_ms', 'action!=ingress'), 'sum', 'source'), 'source')"
    }
   ]
  },
  {
   "title": "Node RAM utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(maxSeries(sortByName(seriesByTag('name=~gauge.node.memory.limit'), true, true)), 'limit')"
    },
    {
     "target": "sortByMaxima(sortByName(aliasByTags(seriesByTag('name=~gauge.node.memory.usage'), 'hostname'), true, true))"
    }
   ]
  },
  {
   "title": "Node CPU utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias(maxSeries(sortByName(seriesByTag('name=~gauge.node.cpu.limit'), true, true)), 'limit')"
    },
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.cpu.usage'), 'hostname'), true, true)"
    }
   ]
  },
  {
   "title": "App RAM utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(removeEmptySeries(seriesByTag('name=~gauge.app.memory')), 'sum', 'app'), 'app')"
    }
   ]
  },
  {
   "title": "App CPU utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mCores" } },
   "targets": [
    {
     "target": "aliasByTags(groupByTags(removeEmptySeries(seriesByTag('name=~gauge.app.cpu')), 'sum', 'app'), 'app')"
    }
   ]
  },
  {
   "title": "RAM by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "target": "sortBy(aliasByTags(groupByTags(removeEmptySeries(seriesByTag('name=~gauge.app.memory', 'namespace!=')), 'sum', 'namespace'), 'namespace'), 'last', true)"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 345 }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 346 }
   ]
  },
  {
   "title": "CPU by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mCore" } },
   "targets": [
    {
     "target": "sortBy(aliasByTags(groupByTags(removeEmptySeries(seriesByTag('name=~gauge.app.cpu', 'namespace!=')), 'sum', 'namespace'), 'namespace'), 'last', true)"
    }
   ]
  },
  {
   "title": "Disk utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "sortByName(aliasByTags(seriesByTag('name=~gauge.node.disk.usage'), 'hostname'), true, true)"
    }
   ]
  },
  {
   "title": "Bytes deleted by policy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=stats_counts.deleted.bytes'), 'policy')"
    }
   ]
  },
  {
   "title": "DeltaFiles deleted by policy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByTags(seriesByTag('name=stats_counts.deleted.files'), 'policy')"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
   "options": {
    "content": "<hr/>\n<h1><center>Processing Node Breakdown</center></h1>"
   }
  },
  {
   "title": "Performance on Node ${nodes:regex}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "repeat": "nodes"
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(maxSeries(sortByName(seriesByTag('name=~gauge.node.memory.limit', 'hostname=${nodes:regex}'), true, true)), 'limit')"
    },
    {
     "target": "alias(sortByMaxima(sortByName(seriesByTag('name=~gauge.node.memory.usage', 'hostname=${nodes:regex}'), true, true)), 'Total RAM')"
    }
   ]
  },
  {
   "title": "Memory utilization over time (${nodes:regex})",
   "type": "timeseries",
   "description": "- Limit is physical RAM on the node\n- \"hostname\" is RAM usage as reported by host OS\n- App RAM is RAM usage as reported by clustermonitor (kubernetes)",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias(maxSeries(seriesByTag('name=~gauge.node.memory.limit', 'hostname=${nodes:regex}')), 'Limit')"
    },
    {
     "target": "alias(sortByMaxima(seriesByTag('name=~gauge.node.memory.usage', 'hostname=${nodes:regex}')), 'Total RAM')"
    },
    {
     "target": "alias(sum(scale(seriesByTag('name=gauge.app.memory', 'node=${nodes:regex}'), 1000000)), 'App RAM')"
    },
    {
     "target": "alias(movingAverage(seriesByTag('name=~gauge.node.memory.usage', 'hostname=${nodes:regex}'), 200), 'Trend')"
    }
   ]
  },
  {
   "title": "App RAM utilization over time (${nodes:regex})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByTags(groupByTags(seriesByTag('name=~gauge.app.memory', 'node=${nodes:regex}'), 'sum', 'app'), 'app'))"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(maxSeries(sortByName(scale(seriesByTag('name=~gauge.node.cpu.limit', 'hostname=${nodes:regex}'), 0.001), true, true)), 'limit')"
    },
    {
     "target": "alias(sortByMaxima(sortByName(scale(seriesByTag('name=~gauge.node.cpu.usage', 'hostname=${nodes:regex}'), 0.001), true, true)), 'Total CPU')"
    }
   ]
  },
  {
   "title": "CPU utilization over time (${nodes:regex})",
   "type": "timeseries",
   "description": "- Limit is physical RAM on the node\n- \"hostname\" is CPU usage as reported by host OS\n- App CPU is CPU usage as reported by clustermonitor (kubernetes)\n- IOWait is CPU usage as reported by Host OS",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "mCore" } },
   "targets": [
    {
     "target": "alias(maxSeries(seriesByTag('name=~gauge.node.cpu.limit', 'hostname=${nodes:regex}')), 'Limit')"
    },
    {
     "target": "alias(seriesByTag('name=~gauge.node.cpu.usage', 'hostname=${nodes:regex}'), 'Total CPU')"
    },
    {
     "target": "alias(sum(seriesByTag('name=gauge.app.cpu', 'node=${nodes:regex}')), 'App CPU')"
    },
    {
     "target": "alias(seriesByTag('name=~gauge.node.cpu.iowait', 'hostname=${nodes:regex}'), 'IO Wait')"
    },
    {
     "target": "alias(movingAverage(seriesByTag('name=~gauge.node.cpu.usage', 'hostname=${nodes:regex}'), 100), 'Trend')"
    }
   ]
  },
  {
   "title": "App CPU utilization over time (${nodes:regex})",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "mCore" } },
   "targets": [
    {
     "target": "removeEmptySeries(aliasByTags(seriesByTag('name=~gauge.app.cpu', 'node=${nodes:regex}'), 'app'))"
    }
   ]
  }
 ]
}