spring:
  application:
    name: deltafi-ingress
  config:
    import: configserver:http://deltafi-core-service/config
  main:
    banner-mode: "off"

logging:
  level:
    org.springframework.data.convert.CustomConversions: ERROR
