"%dev":
  quarkus:
    http:
      port: 8085
    log:
      level: INFO
      console:
        json: false
        color: true
    minio:
      url: http://localhost:9000
    kubernetes-config:
      enabled: false
  deltafi:
    dgs:
      url: http://localhost:8080/graphql
    zipkin:
      enabled: ${ZIPKIN_ENABLED:false}
      url: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

quarkus:
  http:
    port: 8085
  log:
    level: INFO
    console:
      json: true
      color: true
  minio:
    url: ${MINIO_URL:http://deltafi-minio}
    access-key: ${MINIO_ACCESS:minioadmin}
    secret-key: ${MINIO_SECRET:minioadmin}
  kubernetes-config:
    enabled: true
    fail-on-missing-config: false
    namespace: ${ACTION_NAMESPACE:deltafi}
    config-maps: ${ACTION_CONFIG_MAP:global-actions-config}

deltafi:
  dgs:
    url: ${DELTAFI_DGS_URL:http://deltafi-apollo-gateway-service}
  action_polling_start_delay_ms: 3000
  action_polling_frequency_ms: 100
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    url: ${ZIPKIN_URL:http://deltafi-zipkin:9411/api/v2/spans}
    initialDelayInMilli: ${ZIPKIN_INITIAL_DELAY:500}
    sendFrequencyInMilli: ${ZIPKIN_FREQUENCY:500}
    maxBatchSize: ${ZIPKIN_MAX_BATCH_SIZE:10000}
redis:
  url: ${REDIS_URL:http://deltafi-redis-master:6379}
  password: ${REDIS_PASSWORD:}
