#!/bin/bash

function sync() {
  local name="$1"
  local gitRepo="$2"
  local gitRepoTag="$3"

  echo "Sync $name $gitRepoTag from $gitRepo"
  rm -rf "charts/$name"
  git clone -c advice.detachedHead=false -q --depth 1 --branch "$gitRepoTag" "$gitRepo" "charts/$name"
  rm -rf "charts/$name/.git"
  yq e ".dependencies[] |= select(.name == \"$name\").version=\"$gitRepoTag\"" -i Chart.yaml

}

function sync_oci() {
  local chartName="$1"
  local localName="$2"
  local ociRepo="$3"
  local version="$4"

  echo "Sync $chartName (as $localName) $version from $ociRepo"
  rm -rf "charts/$localName"
  helm pull "$ociRepo/$chartName" --version "$version" --untar --untardir charts
  # Rename if chart name differs from local name
  if [ "$chartName" != "$localName" ]; then
    mv "charts/$chartName" "charts/$localName"
  fi
  yq e ".dependencies[] |= select(.name == \"$localName\").version=\"$version\"" -i Chart.yaml

}

sync grafana https://gitlab.com/deltafi/helmcharts/grafana.git 7.0.17
sync kubernetes-dashboard https://gitlab.com/deltafi/helmcharts/kubernetes-dashboard.git 6.0.8
sync loki https://gitlab.com/deltafi/helmcharts/loki.git 2.16.0
sync_oci victoria-metrics-single victoriametrics oci://ghcr.io/victoriametrics/helm-charts 0.25.4
sync minio https://gitlab.com/deltafi/helmcharts/minio.git 5.0.9
sync promtail https://gitlab.com/deltafi/helmcharts/promtail.git 6.15.2
sync redis https://gitlab.com/deltafi/helmcharts/redis.git 18.4.0
#sync postgresql https://gitlab.com/deltafi/helmcharts/postgresql.git 16.7.19
