apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: action-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["minio-keys", "redis-password"]
  verbs: ["get"]
