apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-role
rules:
- apiGroups: ["metrics.k8s.io", ""]
  resources: ["nodes", "pods", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
