apiVersion: v1
kind: ConfigMap
metadata:
  name: deltafi-status-checks
  namespace: deltafi
data:
  StatefulSetCheck: |
    expected_stateful_sets:
    - deltafi-graphite
    - deltafi-redis-master
  DeploymentCheck: |
    expected_deployments:
    - deltafi-api
    - deltafi-core-actions
    - deltafi-core-domain
    - deltafi-egress-sink
    - deltafi-grafana
    - deltafi-ingress
    - deltafi-kibana
    - deltafi-kubernetes-dashboard
    - deltafi-minio
    - deltafi-mongodb
    - deltafi-monitor
    - deltafi-ui
  IngressCheck: |
    expected_ingresses:
    - deltafi-grafana
    - deltafi-graphite
    - deltafi-ingress
    - deltafi-kibana
    - deltafi-kubernetes-dashboard
    - deltafi-minio
    - deltafi-ui-ingress
  ServiceCheck: |
    expected_services:
    - deltafi-api-service
    - deltafi-core-domain-service
    - deltafi-egress-sink-service
    - deltafi-fluentd
    - deltafi-grafana
    - deltafi-graphite
    - deltafi-ingress-service
    - deltafi-kibana
    - deltafi-kubernetes-dashboard
    - deltafi-minio
    - deltafi-mongodb
    - deltafi-redis-headless
    - deltafi-redis-master
    - deltafi-ui-service
    - elasticsearch-master
    - elasticsearch-master-headless
  StorageCheck: |
    expected_volume_claims:
    - deltafi-auth
    - deltafi-egress-sink
    - deltafi-elasticsearch
    - deltafi-minio
    - deltafi-mongodb
