apiVersion: v1
kind: ConfigMap
metadata:
  name: deltafi-status-checks
  namespace: deltafi
data:
  StatefulSet: |
    - deltafi-core-worker
    - deltafi-graphite
    - deltafi-loki
    - deltafi-mongodb
    - deltafi-valkey-master
  Deployment: |
    - deltafi-core
    - deltafi-core-actions
    - deltafi-docs
    - deltafi-egress-sink
    - deltafi-grafana
    - deltafi-ingress
    - deltafi-kubernetes-dashboard
    - deltafi-minio
    - deltafi-monitor
    - deltafi-ui
  Ingress: |
    - deltafi-grafana
    - deltafi-graphite
    - deltafi-ingress
    - deltafi-kubernetes-dashboard
    - deltafi-minio
    - deltafi-ui-ingress
  Service: |
    - deltafi-core-service
    - deltafi-egress-sink-service
    - deltafi-grafana
    - deltafi-graphite
    - deltafi-ingress-service
    - deltafi-kubernetes-dashboard
    - deltafi-loki
    - deltafi-loki-headless
    - deltafi-loki-memberlist
    - deltafi-minio
    - deltafi-mongodb
    - deltafi-valkey-headless
    - deltafi-valkey-master
    - deltafi-ui-service
  PersistentVolumeClaim: |
    - deltafi-auth
    - deltafi-egress-sink
    - deltafi-grafana
    - deltafi-graphite
    - deltafi-loki
    - deltafi-minio
    - deltafi-mongodb
