apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-gateway
  labels:
    app: deltafi-gateway
    group: deltafi-core
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-gateway
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-gateway
        group: deltafi-core
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/deployment-core-domain.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: wait-for-core-domain
        image: busybox:1.34.1
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 deltafi-core-domain-service 80 && echo deltafi-core-domain ok;
            do sleep 1;
          done
      containers:
      - name: deltafi-gateway
        image: {{ .Values.deltafi.gateway.image }}
        ports:
        - containerPort: 4000
        {{- include "defaultStartupProbe" . | nindent 8 }}
        {{- include "defaultReadinessProbe" . | nindent 8 }}
        {{- include "defaultLivenessProbe" . | nindent 8 }}
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-gateway
