apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-core-actions
  labels:
    app: deltafi-core-actions
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-core-actions
  template:
    metadata:
      labels:
        app: deltafi-core-actions
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox:1.34.1
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 deltafi-config-server 80 && echo config-server ok;
            do sleep 1;
          done
      containers:
      - name: deltafi-core-actions
        image: "{{ .Values.deltafi.core_actions.image }}"
        {{- with .Values.deltafi.envVars }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        startupProbe:
          httpGet:
            port: 8080
            path: /
          periodSeconds: 1
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 45
        livenessProbe:
          httpGet:
            port: 8080
            path: /
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 3
      imagePullSecrets:
      - name: docker-secret
