apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-ingress
  labels:
    app: deltafi-ingress
    group: deltafi-core
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-ingress
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-ingress
        group: deltafi-core
    spec:
      {{- include "initContainersWaitForCore" . | nindent 6 }}
      containers:
      - name: deltafi-ingress
        image: {{ .Values.deltafi.core.image }}
        {{- with .Values.deltafi.envVars }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: JDK_JAVA_OPTIONS
          value: "-Dcom.redhat.fips=false -Dschedule.actionEvents=false -Dschedule.maintenance=false -Dschedule.propertySync=false"
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-passwords
              key: mongodb-password
                {{- with .Values.deltafi.envVars }}
                {{- toYaml . | nindent 8 }}
                {{- end }}
        ports:
        - containerPort: 8080
        {{- include "defaultStartupProbe" . | nindent 8 }}
        {{- include "defaultReadinessProbe" . | nindent 8 }}
        {{- include "defaultLivenessProbe" . | nindent 8 }}
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-auth
      nodeSelector:
        node-role.deltafi.org/storage: "true"