apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-core-actions
  labels:
    app: deltafi-core-actions
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-core-actions
  template:
    metadata:
      labels:
        app: deltafi-core-actions
    spec:
      containers:
      - name: deltafi-core-actions
        image: "{{ .Values.deltafi.core_actions.image }}"
        {{- with .Values.deltafi.envVars }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      imagePullSecrets:
      - name: docker-secret
