apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-core-domain
  labels:
    app: deltafi-core-domain
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-core-domain
  template:
    metadata:
      labels:
        app: deltafi-core-domain
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox:1.34.1
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 deltafi-config-server 80 && echo config-server ok;
            do sleep 1;
          done
      containers:
      - name: deltafi-core-domain
        image: {{ .Values.deltafi.core_domain.image }}
        env:
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-passwords
              key: mongodb-password
          {{- with .Values.deltafi.envVars }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            port: 8080
            path: /graphiql
          periodSeconds: 1
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            port: 8080
            path: /graphiql
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 2
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-core-domain
