apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-core-actions
  labels:
    app: deltafi-core-actions
    group: deltafi-core
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-core-actions
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-core-actions
        group: deltafi-core
    spec:
      initContainers:
      - name: wait-for-config-server
        image: busybox:1.34.1
        command:
        - 'sh'
        - '-c'
        - >
          until nc -z -w 2 deltafi-config-server 80 && echo config-server ok;
            do sleep 1;
          done
      containers:
      - name: deltafi-core-actions
        image: "{{ .Values.deltafi.core_actions.image }}"
        {{- with .Values.deltafi.envVars }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Values.deltafi.core_actions.keyStorePasswordSecret }}
            optional: true
        {{- include "defaultStartupProbe" . | nindent 8 }}
        {{- include "defaultReadinessProbe" . | nindent 8 }}
        {{- include "defaultLivenessProbe" . | nindent 8 }}
        volumeMounts:
          - mountPath: {{ .Values.deltafi.core_actions.keyStoreMountPath }}
            name: keystore
            readOnly: true
      volumes:
        - name: keystore
          secret:
            secretName: {{ .Values.deltafi.core_actions.keyStoreSecret }}
            optional: true
      imagePullSecrets:
      - name: docker-secret
