apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-api
  labels:
    app: deltafi-api
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-api
  template:
    metadata:
      labels:
        app: deltafi-api
    spec:
      containers:
      - name: deltafi-api
        image: {{ .Values.deltafi.api.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9292
        env:
        - name: RACK_ENV
          value: production
        - name: RUNNING_IN_CLUSTER
          value: "true"
        - name: DELTAFI_UI_DOMAIN
          value: {{ .Values.ingress.domain }}
        - name: DELTAFI_UI_TITLE
          value: {{ coalesce .Values.deltafi.ui.title "DeltaFi" }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: redis-password
        - name: MINIO_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: minio-keys
              key: accesskey
        - name: MINIO_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: minio-keys
              key: secretkey
        startupProbe:
          httpGet:
            port: 9292
            path: /api/v1/config
          periodSeconds: 1
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        livenessProbe:
          httpGet:
            port: 9292
            path: /api/v1/config
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 2
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-api
