apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-auth
  labels:
    app: deltafi-auth
    group: deltafi-core
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-auth
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-auth
        group: deltafi-core
    spec:
      {{- include "initContainersWaitForDatabases" . | nindent 6 }}
      volumes:
        {{- include "coreVolumes" . | nindent 8 }}
        - name: deltafi-auth
          persistentVolumeClaim:
            claimName: deltafi-auth
      containers:
      {{ if .Values.deltafi.auth.entityResolver.enabled }}
      - name: deltafi-entity-resolver
        image: {{ .Values.deltafi.auth.entityResolver.image }}
        volumeMounts:
          - name: deltafi-auth
            mountPath: /data
        env:
        - name: DATA_DIR
          value: /data
      {{ end }}
      - name: deltafi-auth
        image: {{ .Values.deltafi.core.image }}
        env:
        - name: SERVER_PORT
          value: "9292"
        - name: JDK_JAVA_OPTIONS
          value: "-Dcom.redhat.fips=false -Dschedule.actionEvents=false -Dschedule.maintenance=false -Dschedule.errorCount=false -Dschedule.flowSync=false -Dschedule.diskSpace=false -Dschedule.pluginSync=false"
        - name: UNIQUE_ID
          value: auth
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        {{- include "coreEnvVars" . | nindent 8 }}
        {{- include "clickhouseEnvVars" . | nindent 8 }}
        {{ if .Values.deltafi.auth.entityResolver.enabled }}
        - name: ENTITY_RESOLVER_ENABLED
          value: "true"
        - name: ENTITY_RESOLVER_URL
          value: {{ .Values.deltafi.auth.entityResolver.url | default "http://127.0.0.1:8080/" }}
        {{ end }}
        envFrom:
        {{- include "keyStorePasswordSecret" . | nindent 8 }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9292
        {{- include "defaultStartupProbe" . | nindent 8 }}
        {{- include "defaultReadinessProbe" . | nindent 8 }}
        {{- include "defaultLivenessProbe" . | nindent 8 }}
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-core
      nodeSelector:
        node-role.deltafi.org/storage: "true"
  strategy:
    type: Recreate
