apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-ui
  labels:
    app: deltafi-ui
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-ui
  template:
    metadata:
      labels:
        app: deltafi-ui
    spec:
      containers:
      - name: deltafi-ui
        image: {{ .Values.deltafi.ui.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: RUNNING_IN_CLUSTER
          value: "true"
        startupProbe:
          httpGet:
            port: 80
            path: /
          periodSeconds: 1
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 45
        livenessProbe:
          httpGet:
            port: 80
            path: /
          periodSeconds: 30
          timeoutSeconds: 20
          successThreshold: 1
          failureThreshold: 2
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-api
