apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-auth
  labels:
    app: deltafi-auth
    group: deltafi-core
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-auth
      group: deltafi-core
  template:
    metadata:
      labels:
        app: deltafi-auth
        group: deltafi-core
    spec:
      volumes:
        - name: deltafi-auth
          persistentVolumeClaim:
            claimName: deltafi-auth
      containers:
      - name: deltafi-auth
        image: {{ .Values.deltafi.auth.image }}
        env:
        - name: DATA_DIR
          value: /data
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9292
        {{- include "defaultStartupProbe" . | nindent 8 }}
        {{- include "defaultReadinessProbe" . | nindent 8 }}
        {{- include "defaultLivenessProbe" . | nindent 8 }}
        volumeMounts:
          - name: deltafi-auth
            mountPath: /data
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-auth
