apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltafi-ingress
  labels:
    app: deltafi-ingress
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: deltafi-ingress
  template:
    metadata:
      labels:
        app: deltafi-ingress
    spec:
      containers:
      - name: deltafi-ingress
        image: {{ .Values.deltafi.ingress.image }}
        {{- with .Values.deltafi.envVars }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-secret
      serviceAccountName: deltafi-auth
