apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deltafi-ui-ingress
  annotations:
  {{- include "authAnnotations" . | nindent 4 }}
spec:
  {{- if eq .Values.ingress.tls.enabled true }}
  tls:
  - secretName: {{ coalesce .Values.ingress.tls.secrets.ui .Values.ingress.tls.secrets.default }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deltafi-ui-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: deltafi-api-service
            port:
              number: 80
      - path: /graphql
        pathType: Prefix
        backend:
          service:
            name: deltafi-gateway-service
            port:
              number: 80
