apiVersion: batch/v1
kind: Job
metadata:
  name: deltafi-minio-configure-buckets
  labels:
    app: minio-configure-buckets-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      labels:
        app: minio-job
        release: deltafi
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: minio-configuration
          projected:
            sources:
            - configMap:
                name: deltafi-minio
            - secret:
                name: minio-keys
      serviceAccountName: "deltafi-minio"
      containers:
      - name: minio-mc
        image: "{{ .Values.minio.mcImage.repository }}:{{ .Values.minio.mcImage.tag }}"
        imagePullPolicy: IfNotPresent
        command: 
        - "/bin/sh"
        - "-c"
        - |
{{ include (print $.Template.BasePath "/_helper_configure_buckets.sh.txt") . | indent 10 }}
        env:
          - name: MINIO_ENDPOINT
            value: deltafi-minio
          - name: MINIO_PORT
            value: {{ .Values.minio.service.port | quote }}
        volumeMounts:
          - name: minio-configuration
            mountPath: /config
