apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deltafi-core-domain
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: edit
subjects:
  - kind: ServiceAccount
    name: deltafi-core-domain
