apiVersion: v1
kind: Service
metadata:
  name: deltafi-egress-sink-service
spec:
  selector:
    app: deltafi-egress-sink
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9292
