apiVersion: v1
kind: Service
metadata:
  name: deltafi-config-server
  labels:
    deltafi-domain-service: "deltafi-properties-domain"
spec:
  selector:
    app: deltafi-config-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888