{{- if .Values.postgres.enabled }}
{{- if .Capabilities.APIVersions.Has "stackgres.io/v1/SGCluster" }}
apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: deltafi-postgres-create-db
  namespace: deltafi
spec:
  managedVersions: true
  continueOnError: false
  scripts:
  - name: create-deltafi-user
    scriptFrom:
      secretKeyRef:
        name: postgres
        key: create-user.sql
  - name: create-deltafi-database
    script: |
      CREATE DATABASE deltafi WITH OWNER deltafi;
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: deltafi-postgres
spec:
  metadata:
    labels:
      clusterPods:
        group: "deltafi-db"
  instances: 1
  postgres:
    version: {{ .Values.postgres.version | default "latest" | quote }}
  pods:
    persistentVolume:
      size: '5Gi'
  managedSql:
    scripts:
    - sgScript: deltafi-postgres-create-db
{{ else }}
{{- required "\n  - postgres is enabled but the Stackgres Operator is not present\n  - Set DELTAFI_STACKGRES_ENABLED to 'true' in deltafi config" "" }}
{{ end }}
{{ end }}
