# DeltaFi config
deltafi:
  keyStore:
    secret: keystore-secret
    passwordSecret: keystore-password-secret
    mountPath: /etc/pki
    keyStoreName: keyStore.p12
    trustStoreName: trustStore.jks
  actions:
    envVars:
      - name: SPRING_CONFIG_IMPORT
        value: configserver:http://deltafi-core-service/config
  envVars:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-password
          key: redis-password
    - name: MINIO_ACCESSKEY
      valueFrom:
        secretKeyRef:
          name: minio-keys
          key: accesskey
    - name: MINIO_SECRETKEY
      valueFrom:
        secretKeyRef:
          name: minio-keys
          key: secretkey
    - name: ACTIONS_HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  core_actions:
    egress_endpoint: http://deltafi-egress-sink-service
    image: deltafi/deltafi-core-actions:0.99.0
  core:
    image: deltafi/deltafi-core:0.99.0
    envVars:
      - name: DELTAFI_CONFIG_IMPORT
        value: deltafi:mongodb=true&git=false
      - name: MONGO_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mongodb-passwords
            key: mongodb-password
    mongo_host: deltafi-mongodb
    nativeConfigMap: config-server-configmap
    nativeConfigMountPath: /config
    # Properties that will be set externally prior to system startup
    propertyOverrides: ~
      # deltafi-common.yaml: |-
      #  deltafi:
      #    properties: here
  docs:
    image: deltafi/deltafi-docs:0.99.0
    enabled: true
  ingress:
    envVar:
      HTTP_MAX_BODY_SIZE: 5G
  auth:
    image: deltafi/deltafi-auth:0.99.0
    mode: basic # basic, cert, or disabled
    secret: auth-secret
  api:
    image: deltafi/deltafi-api:0.99.0
  ui:
    image: deltafi/deltafi-ui:0.99.0
    # UI Configuration
    # title: DeltaFi
    # securityBanner:
    #   enabled: true
    #   backgroundColor: "#007a33"
    #   textColor: "#ffffff"
    #   text: "UNCLASSIFIED"
    # topBar:
    #   backgroundColor: "#003559"
    #   textColor: "#dddddd"
    # externalLinks:
    #   - name: DeltaFi Documentation
    #     url: https://docs.deltafi.org/
    #     description: Official DeltaFi Documentation
    # deltaFileLinks:
    #   - name: "View in HTTPBin"
    #     url: "https://httpbin.org/anything/${did}"
  egress_sink:
    enabled: true
    image: deltafi/deltafi-egress-sink:0.99.0
  nodemonitor:
    image: deltafi/deltafi-nodemonitor:0.99.0
    envVars:
      - name: GRAPHITE_HOST
        value: deltafi-graphite
      - name: GRAPHITE_PORT
        value: "2003"
      - name: PERIOD
        value: "9"

# Kubernetes ingress config
ingress:
  domain: local.deltafi.org
  tls:
    enabled: false
    secrets:
      default: local-deltafi-org
# MinIO config
minio:
  image:
    tag: RELEASE.2022-08-25T07-17-05Z
  existingSecret: minio-keys
  resources:
    requests:
      memory: 2Gi
  replicas: 1
  persistence:
    enabled: true
    existingClaim: deltafi-minio
  ingress:
    enabled: false
  service:
    type: NodePort
    port: 9000
  nodeSelector:
    node-role.deltafi.org/storage: "true"
# Values for the MongoDB dependency
mongodb:
  image:
    repository: bitnami/mongodb
    tag: 5.0.6-debian-10-r0
  architecture: standalone
  useStatefulSet: false
  auth:
    existingSecret: mongodb-passwords
    enabled: true
    database: deltafi
    username: mongouser
  service:
    type: NodePort
  persistence:
    enabled: true
    existingClaim: deltafi-mongodb
  volumePermissions:
    enabled: true
  nodeSelector:
    node-role.deltafi.org/storage: "true"
# Redis config
redis:
  image:
    repository: bitnami/redis
    tag: 7.0.5
  architecture: standalone
  auth:
    existingSecret: redis-password
    enabled: true
  commonConfiguration: |-
    # Diable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence
    save ""
  master:
    persistence:
      enabled: false
    nodeSelector:
      node-role.deltafi.org/compute: "true"
# Kubernetes Dashboard config
kubernetes-dashboard:
  securityContext: null
  metricsScraper:
    enabled: true
  protocolHttp: true
  service:
    externalPort: 80
  settings:
    clusterName: 'DeltaFi'
    itemsPerPage: 50
    labelsLimit: 3
    logsAutoRefreshTimeInterval: 5
    resourceAutoRefreshTimeInterval: 5
    disableAccessDeniedNotifications: false
    defaultNamespace: deltafi
    namespaceFallbackList:
      - default

grafana:
  image:
    tag: 9.1.7
  persistence:
    enabled: true
    existingClaim: deltafi-grafana
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth.basic:
      enabled: false
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: false
      enable_feedback_links: false
    dashboards:
      min_refresh_interval: "10s"
    log:
      mode: console
    log.console:
      format: json
    unified_alerting:
      enabled: true
    alerting:
      enabled: false
    security:
      allow_embedding: true
  sidecar:
    dashboards:
      enabled: true
      provider:
        folder: "DeltaFi"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://deltafi-graphite:8080
        editable: false
        isDefault: true
        version: 2
        uid: deltafi-graphite
      - name: Loki
        type: loki
        access: proxy
        url: http://deltafi-loki:3100
        editable: false
        isDefault: false
        version: 2
        uid: deltafi-loki
promtail:
  image:
    tag: 2.6.1
  persistence:
    enabled: true
    existingClaim: deltafi-promtail
  config:
    clients:
      - url: http://deltafi-loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
        - labeldrop:
            - filename
        # Label action logs
        - match:
            selector: '{ app=~".+" } |~ "\"action\":\"[^\"]+\""'
            stages:
            - json:
                expressions:
                  action: action
            - labels:
                action:
            - static_labels:
                type: 'ACTION'
        # Label audit logs
        - match:
              selector: '{ app=~".*" } |= "\"loggerName\":\"AUDIT\""'
              stages:
              - json:
                  expressions:
                    user: user
              - labels:
                  user:
              - static_labels:
                  type: "AUDIT"
        # Squelch nasty graphite debug logs
        - match:
            selector: '{app="graphite"}'
            stages:
              # Filtering out graphite debug logs containing "(Tagging|Tagged)"
              - drop:
                  expression: "Tagg"

loki:
  image:
    tag: 2.6.1
  persistence:
    enabled: true
    existingClaim: deltafi-loki
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  extraArgs:
    log.level: warn
  config:
    compactor:
      retention_enabled: true
    query_scheduler:
      max_outstanding_requests_per_tenant: 500
  livenessProbe:
   initialDelaySeconds: 5
  readinessProbe:
   initialDelaySeconds: 5

# Graphite Configuration
graphite:
  image:
    tag: 1.1.10-3
  persistence:
    enabled: true
    existingClaim: deltafi-graphite
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  statsd:
    interface: TCP

# Enable a "black hole" service that consumes all HTTP posts with a 200 response on http://deltafi-blackhole-service
blackhole:
  enabled: false
