# DeltaFi config
deltafi:
  ui:
    title: DeltaFi (DinK)
    image: localhost:5000/deltafi-ui:latest
  passthrough_actions:
    image: localhost:5000/deltafi-passthrough-actions:latest
  core_actions:
    image: localhost:5000/deltafi-core-actions:latest
  core:
    image: localhost:5000/deltafi-core:latest
  doc:
    image: localhost:5000/deltafi-doc:latest
  ingress:
    image: localhost:5000/deltafi-ingress:latest
  auth:
    image: localhost:5000/deltafi-auth:latest
    mode: disabled
  api:
    image: localhost:5000/deltafi-api:latest
  egress_sink:
    image: localhost:5000/deltafi-egress-sink:latest
  nodemonitor:
    image: localhost:5000/deltafi-nodemonitor:latest
blackhole:
  enabled: true
