# DeltaFi config
deltafi:
  ui:
    title: DeltaFi (DinK)
  auth:
    mode: disabled
postgres:
  enabled: true
clickhouse:
  enabled: true
registry-ui:
  enabled: true
docker-registry:
  enabled: false
