# DeltaFi config
deltafi:
  ssl:
    secret: keystore-secret
    passwordSecret: keystore-password-secret
    mountPath: /etc/pki
    protocol: TLSv1.2
    keyStoreName: keyStore.p12
    keyStoreType: PKCS12
    trustStoreName: trustStore.jks
    trustStoreType: JKS
  core_actions:
    image: deltafi/deltafi-core-actions:0.101.0
  core:
    image: deltafi/deltafi-core:0.101.0
    mongo_host: deltafi-mongodb
  docs:
    image: deltafi/deltafi-docs:0.101.0
    enabled: true
  ingress:
    envVar:
      HTTP_MAX_BODY_SIZE: 5G
  auth:
    image: deltafi/deltafi-auth:0.101.0
    mode: basic # basic, cert, or disabled
    secret: auth-secret
    entityResolver:
      enabled: false
      image: deltafi/deltafi-entity-resolver:0.101.0
      url: http://127.0.0.1:8080/
  api:
    image: deltafi/deltafi-api:0.101.0
  ui:
    image: deltafi/deltafi-ui:0.101.0
  egress_sink:
    enabled: true
    image: deltafi/deltafi-egress-sink:0.101.0
  nodemonitor:
    image: deltafi/deltafi-nodemonitor:0.101.0
    envVars:
      - name: GRAPHITE_HOST
        value: deltafi-graphite
      - name: GRAPHITE_PORT
        value: "2003"
      - name: PERIOD
        value: "9"

# Kubernetes ingress config
ingress:
  domain: local.deltafi.org
  tls:
    enabled: false
    secrets:
      default: local-deltafi-org
# MinIO config
minio:
  image:
    # Do not change without extensive minio testing and changes to secret handling
    tag: RELEASE.2022-08-25T07-17-05Z
  existingSecret: minio-keys
  resources:
    requests:
      memory: 2Gi
  replicas: 1
  persistence:
    enabled: true
    existingClaim: deltafi-minio
  ingress:
    enabled: false
  service:
    type: NodePort
    port: 9000
  nodeSelector:
    node-role.deltafi.org/storage: "true"
# Values for the MongoDB dependency
mongodb:
  image:
    repository: bitnami/mongodb
    tag: 5.0.14
  architecture: standalone
  useStatefulSet: false
  auth:
    existingSecret: mongodb-passwords
    enabled: true
    database: deltafi
    username: mongouser
  service:
    type: NodePort
  persistence:
    enabled: true
    existingClaim: deltafi-mongodb
  volumePermissions:
    enabled: true
  nodeSelector:
    node-role.deltafi.org/storage: "true"
# Redis config
redis:
  image:
    repository: bitnami/redis
    tag: 7.0.7
  architecture: standalone
  auth:
    existingSecret: redis-password
    enabled: true
  commonConfiguration: |-
    # Diable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence
    save ""
  master:
    persistence:
      enabled: false
    nodeSelector:
      node-role.deltafi.org/compute: "true"
# Kubernetes Dashboard config
kubernetes-dashboard:
  securityContext: null
  metricsScraper:
    enabled: true
  protocolHttp: true
  service:
    externalPort: 80
  settings:
    clusterName: 'DeltaFi'
    itemsPerPage: 50
    labelsLimit: 3
    logsAutoRefreshTimeInterval: 5
    resourceAutoRefreshTimeInterval: 5
    disableAccessDeniedNotifications: false
    defaultNamespace: deltafi
    namespaceFallbackList:
      - default

grafana:
  image:
    tag: 9.3.2
  persistence:
    enabled: true
    existingClaim: deltafi-grafana
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth.basic:
      enabled: false
    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: false
      enable_feedback_links: false
    dashboards:
      min_refresh_interval: "10s"
    log:
      mode: console
    log.console:
      format: json
    unified_alerting:
      enabled: true
    alerting:
      enabled: false
    security:
      allow_embedding: true
  sidecar:
    dashboards:
      enabled: true
      provider:
        folder: "DeltaFi"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Graphite
        type: graphite
        access: proxy
        url: http://deltafi-graphite:8080
        editable: false
        isDefault: true
        version: 2
        uid: deltafi-graphite
      - name: Loki
        type: loki
        access: proxy
        url: http://deltafi-loki:3100
        editable: false
        isDefault: false
        version: 2
        uid: deltafi-loki
promtail:
  image:
    tag: 2.7.1
  persistence:
    enabled: true
    existingClaim: deltafi-promtail
  config:
    clients:
      - url: http://deltafi-loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
        - labeldrop:
            - filename
        # Label action logs
        - match:
            selector: '{ app=~".+" } |~ "\"action\":\"[^\"]+\""'
            stages:
            - json:
                expressions:
                  action: action
            - labels:
                action:
            - static_labels:
                type: 'ACTION'
        # Label audit logs
        - match:
              selector: '{ app=~".*" } |= "\"loggerName\":\"AUDIT\""'
              stages:
              - json:
                  expressions:
                    user: user
              - labels:
                  user:
              - static_labels:
                  type: "AUDIT"
        # Squelch nasty graphite debug logs
        - match:
            selector: '{app="graphite"}'
            stages:
              # Filtering out graphite debug logs containing "(Tagging|Tagged)"
              - drop:
                  expression: "Tagg"

loki:
  image:
    tag: 2.7.1
  persistence:
    enabled: true
    existingClaim: deltafi-loki
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  extraArgs:
    log.level: warn
  config:
    compactor:
      retention_enabled: true
    query_scheduler:
      max_outstanding_requests_per_tenant: 500
  livenessProbe:
   initialDelaySeconds: 5
  readinessProbe:
   initialDelaySeconds: 5

# Graphite Configuration
graphite:
  image:
    tag: 1.1.10-4
  persistence:
    enabled: true
    existingClaim: deltafi-graphite
  nodeSelector:
    node-role.deltafi.org/storage: "true"
  statsd:
    interface: TCP

# Enable a "black hole" service that consumes all HTTP posts with a 200 response on http://deltafi-blackhole-service
blackhole:
  enabled: false
