server:
  port: 8888
spring:
  cloud:
    config:
      server:
        # add native profile to use local directory instead of a git repo
        native:
          search-locations: ${NATIVE_SEARCH_LOCATIONS:file:./config/}
        git:
          uri: ${GIT_CONFIG_REPO:https://gitlab.com/systolic/deltafi/deltafi-config.git}
          username: ${USERNAME:config-server}
          password: ${CONFIG_TOKEN}
          clone-on-start: ${CLONE_ON_START:true}
          private-key: ${PRIVATE_KEY}
          ignore-local-ssh-settings: ${IGNORE_LOCAL_SSH_SETTINGS:true}
          strict-host-key-checking: ${STRICT_HOST_KEY_CHECKING:false}
        default-label: ${DEFAULT_LABEL:main}
  data:
    mongodb:
      host: ${MONGO_HOST:deltafi-mongodb}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:deltafi}
      username: ${MONGO_USERNAME:mongouser}
      password: ${MONGO_PASSWORD}
      authentication-database: ${MONGO_AUTH_DB:deltafi}
      auto-index-creation: true
