apiVersion: v1
kind: Service
metadata:
  name: deltafi-core-service
  labels:
    deltafi-service: "deltafi-core"
spec:
  selector:
    role: api
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9292
