.auth:
  needs: []
  variables:
    PROJECT_NAME: deltafi-auth

auth:docker:
  extends:
    - .auth
    - .docker
  # after_script:
  #   - docker run --rm ${DOCKER_TAG} bundle exec rspec --format doc

auth:docker-multiarch:
  extends:
    - .auth
    - .docker-multiarch
