.auth:
  variables:
    PROJECT_NAME: deltafi-auth

auth:docker:
  stage: docker
  extends:
    - .auth
    - .docker
  after_script:
    - docker run --rm ${DOCKER_TAG} bundle exec rspec --format doc
