# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt'
gem 'eventmachine'
gem 'httparty'
gem 'rainbows'
gem 'sequel'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sqlite3', '~> 1.4.4'

group :test, :development do
  gem 'pry'
  gem 'rack-test'
  gem 'rerun'
  gem 'rspec', '~> 3.0'
end
