spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: ${MONGO_AUTH_DB:admin}
      auto-index-creation: true
  profiles:
    active: k8s
deltafi:
  requeueSeconds: 30
  delete:
    onCompletion: false
    frequency: PT1M
    policies:
      oneHourAfterComplete:
        type: ageOff
        parameters:
          afterComplete: PT1H
  configSource:
    flows: RELOAD_FROM_PROPERTY
    actions: RELOAD_FROM_PROPERTY
    path: ${CONFIG_SOURCE_PATH:file:/config/bootstrap-config.yaml}
  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    url: ${ZIPKIN_URL:http://deltafi-zipkin:9411/api/v2/spans}
    initialDelayInMilli: ${ZIPKIN_INITIAL_DELAY:500}
    sendFrequencyInMilli: ${ZIPKIN_FREQUENCY:500}
    maxBatchSize: ${ZIPKIN_MAX_BATCH_SIZE:10000}
redis:
  url: ${REDIS_URL:http://localhost:6379}
  password: ${REDIS_PASSWORD:}
